### ISSUE TITLE
Stereo Calibration Related

### ISSUE THREAD

**Issue by WAH0731** [dicengine/dice#100]
I use DICe V2 Beta12 on windows 10. 
Problem is that I can't load calibraion pictures, it's like nothing is there in the folder when I ran perform cal, I can't see pictures or select them. 
I tried .bmp and .jpg and .png, none of them work.

**Comment by CaesarTheFox** [comment]
Maybe you should check the names of the image pairs. You can try the calibration pictures in example 'stereo_d_sample'

**Comment by WAH0731** [comment]
> Maybe you should check the names of the image pairs. You can try the calibration pictures in example 'stereo_d_sample'

**Comment by WAH0731** [comment]
> Maybe you should check the names of the image pairs. You can try the calibration pictures in example 'stereo_d_sample'

I can't even open pics in the example file actually.
This is the error reporting maybe
![1](https://user-images.githubusercontent.com/44606834/50589964-bd5e5b80-0ec3-11e9-87c1-aeab8d678347.png)

**Comment by dicengine** [comment]
I'm not sure what's going on with this, but do you get the same message if you close all instances of DICe, start a new instance and try to load the calibration images?
