### ISSUE TITLE
JavaScript Error Stereo Calibration related (re-submit), attempting to call a function in a renderer window that has been closed

### ISSUE THREAD

**Issue by WAH0731** [dicengine/dice#102]
I can't see any picture in any folder (even in the DIC example file)  when I select picture in perform calib.
I use windows 10, DICe version 2 beta 12. 
This maybe is the error report 
![1](https://user-images.githubusercontent.com/44606834/50674951-a899d900-1025-11e9-9486-d2d3c93a31fc.png)

**Comment by dicengine** [comment]
Can you give some details on the exact steps leading up to the error? This would help in debugging what's going on.

**Comment by WAH0731** [comment]
I found that Calib piuctures can still be loaded MANUALLY, the previous issue is that I can't see pictures preview in the file folder that is opened by clibration.
The error report I post occurs when I close the whole program. It did not occur any more as I just tried it, but happened beforehand and on some of  my collegues' pc as well.
Sorry for late reply, was prepraring for exam ....

**Comment by WAH0731** [comment]
and btw I had install/uninstall the exe several times and it occured as well
