### ISSUE TITLE
When I open DICe，an error window pops up.

### ISSUE THREAD

**Issue by ZikkyZhou** [dicengine/dice#105]
Hi!
When I open DICe, the following error window pops up.
![image](https://user-images.githubusercontent.com/34936470/53091691-929c9500-354d-11e9-9187-323a92c885b6.png)
When I click "perform cal", an other error window pops up.
![image](https://user-images.githubusercontent.com/34936470/53092056-ae546b00-354e-11e9-8656-6ee7044d7609.png)
I don't know how to deal with it.

**Comment by dicengine** [comment]
Hi,

If you installed DICe in a folder other than the default folder, you need to modify the global.js file that tells the GUI where the executables are. If you installed DICe in the default folder, try deleting the .dice.js file in your home directory and running DICe again.

Thanks,
Dan

On Feb 20, 2019, at 5:35 AM, ZikkyZhou <notifications@github.com<mailto:notifications@github.com>> wrote:


When I open DICe, the following error window pops up.
[image]<https://user-images.githubusercontent.com/34936470/53091691-929c9500-354d-11e9-9187-323a92c885b6.png>
When I click "perform cal", an other error window pops up.
[image]<https://user-images.githubusercontent.com/34936470/53092056-ae546b00-354e-11e9-8656-6ee7044d7609.png>

System Info: windows7 x64

**Comment by ZikkyZhou** [comment]
Thank you for help! It works!
