### ISSUE TITLE
a possible error in Simplex method

### ISSUE THREAD

**Issue by dongzi666** [dicengine/dice#110]
simplex method has reflected point, extended point and so on.
This may be the case of extended point in Line207 of DICe_Simplex.cpp.
Only "fac = -2.0" agrees with the  the case of extended point, but in DICe_Simplex.cpp, "fac = 2.0". 
Please check it.

**Comment by dicengine** [comment]
The implementation in DICe for the simplex method follows that of "Numerical Recipes in C++" by Press et. al., 3rd edition (See pages 505 and 506). I've verified that we have that implementation correct. If you have a reference for another implementation or results that suggest changing fac=2.0 to fac=-2.0 in line 207 of DICe_Simplex.cpp leads to better results, please share.
