### ISSUE TITLE
Enable image thresholding and other histogram balancing for feature matching initializer

### ISSUE THREAD

**Issue by Pulsar9000** [dicengine/dice#112]
Since my experiment required high rates of acquisition, I tried to decrease the exposure to 0.1ms (least possible with my camera). I have attached few images as example wherein Dice failed to work.

However, when I tried cv2 adaptive threshold, Dice works, I have attached those images as well.

_grey = cv2.equalizeHist(img)
thresh = cv2.adaptiveThreshold(grey,255,cv2.ADAPTIVE_THRESH_GAUSSIAN_C,cv2.THRESH_BINARY,5001,2)
cv2.imwrite('output', thresh)_

Take a look and hope to see it implemented in your way. 
[Dice.zip](https://github.com/dicengine/dice/files/3069195/Dice.zip)

**Comment by dicengine** [comment]
I'm not sure I understand exactly what the issue is, can you say more about what you mean by "DICe failed to work"? Do you have some console output or a screen capture that shows what happens?
Some more info would be helpful.
Thanks

**Comment by Pulsar9000** [comment]
I was expecting you to run the files that I sent to see the error for yourself. Nevertheless, I have attached a screen shot of the error. Also refer issue #95

![image](https://user-images.githubusercontent.com/45360452/56021583-1da63a00-5d0a-11e9-8b6f-4a1911ac7686.png)

**Comment by Pulsar9000** [comment]
I understand you have a busy schedule, I want to make sure you understood the issue. 

Feature detection technic failed to work for the images attached in the folder **...\Dice.zip\Dice\Before_TH**. The error statement is  shown below.
![image](https://user-images.githubusercontent.com/45360452/58936591-66a9c600-8770-11e9-893c-5720921f43ea.png)

However, when I apply a threshold manually using the python commands mentioned below, I get the images stored in **...\Dice.zip\Dice\After_TH**

_grey = cv2.equalizeHist(img)
thresh = cv2.adaptiveThreshold(grey,255,cv2.ADAPTIVE_THRESH_GAUSSIAN_C,cv2.THRESH_BINARY,5001,2)
cv2.imwrite('output', thresh)_

In my opinion, the threshold limit should be adjusted to obtain good results on these images. 

Thank you for understanding, ping me for further clarification. 

P.S.: The images were clicked at low exposure 0.1 and high frequency.

**Comment by dicengine** [comment]
I’ll see how hard it would be to let the user override the defaults for the feature matching.

On Jun 5, 2019, at 12:02 AM, Pulsar9000 <notifications@github.com<mailto:notifications@github.com>> wrote:


I understand you have a busy schedule, I want to make sure you understood the issue.

Feature detection technic failed to work for the images attached in the folder ...\Dice.zip\Dice\Before_TH. The error statement is shown below.
[image]<https://user-images.githubusercontent.com/45360452/58936591-66a9c600-8770-11e9-893c-5720921f43ea.png>

However, when I apply a threshold manually using the python commands mentioned below, I get the images stored in ...\Dice.zip\Dice\After_TH

grey = cv2.equalizeHist(img)
thresh = cv2.adaptiveThreshold(grey,255,cv2.ADAPTIVE_THRESH_GAUSSIAN_C,cv2.THRESH_BINARY,5001,2)
cv2.imwrite('output', thresh)

In my opinion, the threshold limit should be adjusted to obtain good results on these images.

Thank you for understanding, ping me for further clarification.

P.S.: The images were clicked at low exposure 0.1 and high frequency.

**Comment by dicengine** [comment]
I think i understand more now what you are looking for. You just want to be able to apply things like an adaptive threshold to the images in DICe before they get processed in the feature matching initializer. It's not really about the feature matching threshold, but pre-processing to help the feature matching be more effective. There might be a way to add an option to the feature matching to enable this. Let me see how hard this would be (you can disregard my last comment)

**Comment by Pulsar9000** [comment]
Yes you're right. Currently I'm preprocessing my images using external commands before using Dice. It would be fantastic if Dice application can do it automatically. Thanks for your reply.

**Comment by dicengine** [comment]
Thresholding before feature matching is now enabled in release 2.0-beta.13. The user can select Feature Matching W/Thresh as the initialization option and then specify the block size to use in the thresholding.

**Comment by Pulsar9000** [comment]
This is a wonderful update, It's very useful and effective. I have tested over 50,000 images, it works flawlessly. I was wondering if you could make this default. For example if feature detection fails instead of error as num_matches < 10, it could automatically switch to the second option or propose it as suggestion. This will make other users aware of this very useful feature.

**Comment by dicengine** [comment]
Thanks for the idea. I added more to the error message for now that explains a threshold can be used. I'll see how hard it would be to automate using the thresholding. The hard part is getting the block size right.
