### ISSUE TITLE
I have a trouble in building Trilinos in windows

### ISSUE THREAD

**Issue by dongzi666** [dicengine/dice#113]
I spend much time on building Trilinos in Windows. The build tool I used is MinGW Makefiles and the result is failed to build.
Here is my cmake script:
cmake ^
-D CMAKE_INSTALL_PREFIX:PATH="D:\packages_build\build_trilinos-12-2-2\INSTALL" ^
-D CMAKE_BUILD_TYPE:STRING=RELEASE ^
-D Trilinos_ENABLE_EXPLICIT_INSTANTIATION:BOOL=ON ^
-D Trilinos_ASSERT_MISSING_PACKAGES=OFF ^
-D Trilinos_ENABLE_ALL_PACKAGES:BOOL=OFF ^
-D Trilinos_ENABLE_ALL_OPTIONAL_PACKAGES:BOOL=OFF ^
-D Trilinos_ENABLE_ALL_FORWARD_DEP_PACKAGES:BOOL=OFF ^
-D TPL_ENABLE_Pthread:BOOL=OFF ^
-D TPL_ENABLE_Boost:BOOL=OFF ^
-D TPL_ENABLE_MPI:BOOL=OFF ^
-D Trilinos_ENABLE_Fortran:BOOL=OFF ^
-D CMAKE_VERBOSE_MAKEFILE:BOOL=FALSE ^
-D TPL_ENABLE_BLAS:BOOL=ON ^
-D BLAS_LIBRARY_DIRS:PATH="D:\packages_installed\CLAPACK_GNU2MS\lib" ^
-D TPL_BLAS_LIBRARIES:STRING="blas;libf2c" ^
-D TPL_ENABLE_LAPACK:BOOL=ON ^
-D LAPACK_LIBRARY_DIRS:PATH="D:\packages_installed\CLAPACK_GNU2MS\lib" ^
-D TPL_BLAS_LIBRARIES:STRING="lapack" ^
-D Trilinos_ENABLE_TeuchosCore:BOOL=ON ^
-D Trilinos_ENABLE_TeuchosComm:BOOL=ON ^
-D Trilinos_ENABLE_TeuchosParameterList:BOOL=ON ^
-D Trilinos_ENABLE_TeuchosNumerics:BOOL=ON ^
-D Trilinos_ENABLE_Epetra:BOOL=ON ^
-D Trilinos_ENABLE_CXX11:BOOL=ON ^
-D Trilinos_ENABLE_TESTS:BOOL=OFF ^
-D CMAKE_C_COMPILER:PATH="C:\Qt\Qt5.8.0\Tools\mingw530_32\bin\gcc.exe" ^
-D CMAKE_CXX_COMPILER:PATH="C:\Qt\Qt5.8.0\Tools\mingw530_32\bin\g++.exe" ^
-G "MinGW Makefiles" ^
"D:\packages\trilinos-12.2.2-Source"

And here is the screen shot  of the result:
![result](https://user-images.githubusercontent.com/21332197/56076181-5de7e400-5e00-11e9-9746-08ccfb38e50e.png)

I don't konw how to solve this problem. It has bothered me for a long time. Please help me out.

**Comment by dicengine** [comment]
Are you able to provide more useful information about the build errors that you are seeing? That will help in figuring out what is going wrong.

On Apr 12, 2019, at 9:31 PM, dongzi666 <notifications@github.com<mailto:notifications@github.com>> wrote:


I spend much time on building Trilinos in Windows. The build tool I used is Visual Studio 2013 and the result is failed to build.
Can you show me how to build in Visual Studio 2013 and give me the detailed building process. If it's convenient for you， can you show me the build process step by step. I do thank you very much. The build problem has perplexed me for a long time, then I can't continue build DICe. Looking forward to your reply.

**Comment by dicengine** [comment]
The problem is that Trilinos doesn't build with MinGW, you have to use visual studio. Sorry that this is the case. Hopefully you can use the visuals studio compilers.

**Comment by dongzi666** [comment]
As you said, I have changed the build tool to visual studio. I followed the steps in http://dicengine.github.io/dice/#BuildingDICe  as below:
![image](https://user-images.githubusercontent.com/21332197/56844622-d01ef500-68e5-11e9-9535-39fd51d74db3.png)
I builded the clapack succesfully. And the next step, I can't find do-trilinos-cmake-win.bat file is provided in the \dice\scripts folder. So I use the trilinos-windows-epetra.bat file in \dice\scripts folder.  Here is the content of  trilinos-windows-epetra.bat :
cmake -D CMAKE_INSTALL_PREFIX:PATH=<path_to_where_trilinos_will_be_installed> -D CMAKE_BUILD_TYPE:STRING=RELEASE -D Trilinos_ENABLE_EXPLICIT_INSTANTIATION:BOOL=ON -D Trilinos_ASSERT_MISSING_PACKAGES=OFF -D Trilinos_ENABLE_ALL_PACKAGES:BOOL=OFF -D Trilinos_ENABLE_ALL_OPTIONAL_PACKAGES:BOOL=OFF -D Trilinos_ENABLE_ALL_FORWARD_DEP_PACKAGES:BOOL=OFF -D TPL_ENABLE_Pthread:BOOL=OFF -D TPL_ENABLE_Boost:BOOL=OFF -D TPL_ENABLE_MPI:BOOL=OFF -D Trilinos_ENABLE_Fortran:BOOL=OFF -D CMAKE_VERBOSE_MAKEFILE:BOOL=FALSE -D Trilinos_ENABLE_TeuchosCore:BOOL=ON -D Trilinos_ENABLE_TeuchosParameterList:BOOL=ON -D Trilinos_ENABLE_TeuchosNumerics:BOOL=ON -D Trilinos_ENABLE_CXX11:BOOL=ON -D Trilinos_ENABLE_Epetra:BOOL=ON  -D Trilinos_ENABLE_OpenMP:BOOL=ON -D BLAS_LIBRARY_DIRS:PATH="<path_to_clapack>\BLAS\SRC" -D LAPACK_LIBRARY_DIRS:PATH="<path_to_clapack>\build_intel\SRC" -DTrilinos_ENABLE_TESTS:BOOL=ON -D CMAKE_C_COMPILER:PATH="C:\Program Files (x86)\Intel\Composer XE 2015\bin\intel64\icl.exe" -D CMAKE_CXX_COMPILER:PATH="C:\Program Files (x86)\Intel\Composer XE 2015\bin\intel64\icl.exe" -DCMAKE_C_COMPILER_ID="Intel" -DCMAKE_C_COMPILER_VERSION="15.0.1.148" -DCMAKE_CXX_COMPILER_ID="Intel" -DCMAKE_CXX_COMPILER_VERSION="15.0.1.148" -DCMAKE_EXE_LINKER_FLAGS:STRING="<path_to_clapack>\F2CLIBS\libf2c\libf2c.lib" -G "NMake Makefiles" ..
In this file, the c and c++ compiler is icl.exe. No icl.exe is installed in my computer. Then I changed the file as below:
cmake -D CMAKE_INSTALL_PREFIX:PATH=D:\DICE_RELATION\trilinos-12.4.2-Source\BUILD\INSTALL -D CMAKE_BUILD_TYPE:STRING=RELEASE -D Trilinos_ENABLE_EXPLICIT_INSTANTIATION:BOOL=ON -D Trilinos_ASSERT_MISSING_PACKAGES=OFF -D Trilinos_ENABLE_ALL_PACKAGES:BOOL=OFF -D Trilinos_ENABLE_ALL_OPTIONAL_PACKAGES:BOOL=OFF -D Trilinos_ENABLE_ALL_FORWARD_DEP_PACKAGES:BOOL=OFF -D TPL_ENABLE_Pthread:BOOL=OFF -D TPL_ENABLE_Boost:BOOL=OFF -D TPL_ENABLE_MPI:BOOL=OFF -D Trilinos_ENABLE_Fortran:BOOL=OFF -D CMAKE_VERBOSE_MAKEFILE:BOOL=FALSE -D Trilinos_ENABLE_TeuchosCore:BOOL=ON -D Trilinos_ENABLE_TeuchosParameterList:BOOL=ON -D Trilinos_ENABLE_TeuchosNumerics:BOOL=ON -D Trilinos_ENABLE_CXX11:BOOL=ON -D Trilinos_ENABLE_Epetra:BOOL=ON  -D Trilinos_ENABLE_OpenMP:BOOL=ON -D BLAS_LIBRARY_DIRS:PATH="D:\DICE_RELATION\clapack-3.2.1-CMAKE\BLAS\SRC" -D LAPACK_LIBRARY_DIRS:PATH="D:\DICE_RELATION\clapack-3.2.1-CMAKE\SRC" -DTrilinos_ENABLE_TESTS:BOOL=ON -D CMAKE_C_COMPILER:PATH="C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\cl.exe" -D CMAKE_CXX_COMPILER:PATH="C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\cl.exe" -DCMAKE_EXE_LINKER_FLAGS:STRING="D:\DICE_RELATION\clapack-3.2.1-CMAKE\F2CLIBS\libf2c\libf2c.lib" -G "NMake Makefiles" ..

Then I  command "trilinos-windows-epetra.bat" in commad line.
![1](https://user-images.githubusercontent.com/21332197/56844904-f1ceab00-68ea-11e9-95e2-0f35e299ae6c.png)
![3](https://user-images.githubusercontent.com/21332197/56844905-f8f5b900-68ea-11e9-8b6b-01231e4c439e.png)
![4](https://user-images.githubusercontent.com/21332197/56844908-feeb9a00-68ea-11e9-820b-42718510164f.png)
![5](https://user-images.githubusercontent.com/21332197/56844916-0743d500-68eb-11e9-9f37-0bda4206f111.png)
![6](https://user-images.githubusercontent.com/21332197/56844917-0d39b600-68eb-11e9-8658-d63fc4fd62d1.png)
![7](https://user-images.githubusercontent.com/21332197/56844918-1165d380-68eb-11e9-909d-25e8d7f422e6.png)
After configuring and generating, execute "nmake" in command line
![8](https://user-images.githubusercontent.com/21332197/56844924-42460880-68eb-11e9-873a-3707cbf2a326.png)
![9](https://user-images.githubusercontent.com/21332197/56844925-4e31ca80-68eb-11e9-984d-71e571123eb9.png)
I don't know how to resolve this problem. Maybe  trilinos-windows-epetra.bat I changed exists error.
Please help me to build trilinos in windows.

**Comment by dicengine** [comment]
First of all an apology: building Trilinos on Windows is quite frustrating and involves some manual steps. We have lobbied for a while to get Windows as a supported platform for Trilinos, but have not been successful. That being said, Windows is not a great development environment and I would encourage you to use Linux or Mac, although I know that's not always an option. 

Here are a couple more pointers that have helped people build Trilinos on windows in the past.
1. Try using as close a version as you can find to the one listed on the build instructions page for DICe (12.2).
2. I will copy the windows cmake file used in the nightly testing into another comment in this issue so you can try using that one.
3. You have to build Trilinos in two stages if you want the global methods in DICe to work (they require exodusII in Trilinos, which only partially builds)
3a. Start with the cmake script below as is and build Trilinos and be sure to execute "nmake install"  to copy all the build products to the install directory.
3b. modify the cmake script to turn SEACAS on and build Trilinos again. This time it will fail just after compiling the exodus library.
3c. Copy the exodus.lib from trilinos/build/packages/seacas/libraries/exodus to your trilinos/install/lib/ directory and exodus_config.h to trilinos/install/include. Copy the exodusII.h and exodus_par.h files from trilinos/packages/seacas/libraries/exodus/include to trilinos/install/include
4. If you make it this far pat yourself on the back and go on to building DICe.

If you get a compiler error for exodusII you might need to add the following code to exodusII.h:
#ifdef WIN32
#define snprintf _snprintf
#endif

One other point is that I have built Trilinos on Windows 10 with VS17, but not VS18.

**Comment by dicengine** [comment]
:: call "C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\amd64\vcvars64.bat"
cmake -D CMAKE_INSTALL_PREFIX:PATH=<path_to_trilinos>\trilinos\build_serial_release\install -D CMAKE_BUILD_TYPE:STRING=RELEASE -D Trilinos_ASSERT_MISSING_PACKAGES=OFF -D Trilinos_ENABLE_ALL_PACKAGES:BOOL=OFF -D Trilinos_ENABLE_ALL_OPTIONAL_PACKAGES:BOOL=OFF -D Trilinos_ENABLE_ALL_FORWARD_DEP_PACKAGES:BOOL=OFF -D TPL_ENABLE_Pthread:BOOL=OFF  -D TPL_ENABLE_Matio:BOOL=OFF -D TPL_ENABLE_X11:BOOL=OFF -D TPL_ENABLE_MPI:BOOL=OFF -D Trilinos_ENABLE_Fortran:BOOL=OFF -D CMAKE_VERBOSE_MAKEFILE:BOOL=FALSE -D Trilinos_ENABLE_SEACAS:BOOL=OFF -D Trilinos_ENABLE_SEACASExodus:BOOL=OFF -D Netcdf_LIBRARY_DIRS="C:\Program Files\netCDF 4.4.1.1\lib" -D Netcdf_INCLUDE_DIRS="C:\Program Files\netCDF 4.4.1.1\include" -D Trilinos_ENABLE_Belos:BOOL=ON -D Trilinos_ENABLE_Ifpack:BOOL=ON -D Trilinos_ENABLE_Ifpack2:BOOL=OFF -D Trilinos_ENABLE_TeuchosCore:BOOL=ON -D Trilinos_ENABLE_TeuchosParameterList:BOOL=ON -D Trilinos_ENABLE_TeuchosNumerics:BOOL=ON -D Trilinos_ENABLE_CXX11:BOOL=ON -D Trilinos_ENABLE_Epetra:BOOL=ON  -D Trilinos_ENABLE_OpenMP:BOOL=ON -D BLAS_LIBRARY_DIRS:PATH=<path_to_clapack>\clapack\build_msvc\BLAS\SRC" -D LAPACK_LIBRARY_DIRS:PATH="<path_to_clapack>\clapack\build_msvc\SRC" -DCMAKE_EXE_LINKER_FLAGS:STRING="<path_to_clapack>\clapack\build_msvc\F2CLIBS\libf2c\libf2c.lib" -D Trilinos_GENERATE_REPO_VERSION_FILE=OFF -D Trilinos_GENERATE_REPO_VERSION_FILE=OFF -G "NMake Makefiles" ..

**Comment by dicengine** [comment]
It looks like exodus built fine without adding the #ifdef WIN32 ... code. The need for this code is dependent on which MSVC compiler you use and it looks like the one you're using works fine without the modifications. 

Regarding the missing header files, you may have to search in your source directory for those. I'm not sure why they wouldn't be in the same place because my notes are with regard to building version 12.2.2 as you are using.

**Comment by dicengine** [comment]
It looks like Exodus built fine without adding the #ifdef WIN32 ... code so I would take it out. This code is only needed for certain versions of the MSVC compiler and it looks like the one you are using works without it. Regarding the missing header files you may have to search in the source directory for those. I don't know why they would be in a different place. I'm using Version 12.2.2 same as you.

**Comment by dicengine** [comment]
It looks like Exodus built fine without adding the #ifdef WIN32 ... code so I would take it out. This code is only needed for certain versions of the MSVC compiler and it looks like the one you are using works without it. Regarding the missing header files you may have to search in the source directory for those. I don't know why they would be in a different place. I'm using Version 12.2.2 same as you.

On May 8, 2019, at 8:12 AM, dongzi666 <notifications@github.com<mailto:notifications@github.com>> wrote:


I find exodus.lib in D:\packages_build\build_mvs_trilinos_12-2-2\BUILD\packages\seacas\libraries\exodus\cbind, different from your directory "trilinos/build/packages/seacas/libraries/exodus".
I can't find exodus_config.h in D:\packages_build\build_mvs_trilinos_12-2-2\BUILD\packages\seacas\libraries\exodus\cbind.
Also I can't find exodus_par.h in D:\packages_build\build_mvs_trilinos_12-2-2\packages\seacas\libraries\exodus\cbind\include.
I don't think that the version of trilinos we build is same. The version of trilinos I build is trilinos-12.2.2.
Could you tell me your version?
And provide me the download Link.
Thank you!

**Comment by dongzi666** [comment]
> It looks like exodus built fine without adding the #ifdef WIN32 ... code. The need for this code is dependent on which MSVC compiler you use and it looks like the one you're using works fine without the modifications.
> 
> Regarding the missing header files, you may have to search in your source directory for those. I'm not sure why they wouldn't be in the same place because my notes are with regard to building version 12.2.2 as you are using.

I

**Comment by dongzi666** [comment]
In this situation of mine, which head file I should copy.
And can you provide the download link of your trilinos. There are difference between our trilinos after all.

**Comment by dongzi666** [comment]
Thank you for your cmake script of trilinos. 
I followed the step of building DICe in Windows in http://dicengine.github.io/dice/#BuildingDICe.
At "Building DICe for Windows", the sequence of building DICe is CLAPACK, TRILINOS, OPENCV and DICe. But I found that do-dice-cmake-win.bat in \dice\scripts folder contained “-D NetCDF_DIR:STRING=<path> -D HDF5_DIR:STRING=<path>”
Could you provide me the process of installing NetCDF and HDF5?  And which version is suitable?
Thank you for your reply.

**Comment by dicengine** [comment]
The instructions for installing netcdf are available on the netcdf web page. I’m using NetCDF 4.4.1.1. HDF5 gets installed as part of the netcdf install in the lib directory. You don’t need a separate install for that.

On May 14, 2019, at 8:57 AM, dongzi666 <notifications@github.com<mailto:notifications@github.com>> wrote:


Thank you for your cmake script of trilinos.
I followed the step of building DICe in Windows in http://dicengine.github.io/dice/#BuildingDICe.
At "Building DICe for Windows", the sequence of building DICe is CLAPACK, TRILINOS, OPENCV and DICe. But I found that do-dice-cmake-win.bat in \dice\scripts folder contained “-D NetCDF_DIR:STRING= -D HDF5_DIR:STRING=”
Could you provide me the process of installing NetCDF and HDF5? And which version is suitable?
Thank you for your reply.

**Comment by dongzi666** [comment]
There is an error occured in the last step of building DICe. Here is my cmake script
cmake -D CMAKE_BUILD_TYPE:STRING=RELEASE -D DICE_DEBUG_MSG:BOOL=ON -D CMAKE_INSTALL_PREFIX:FILEPATH="D:\packages_build\dice-2.0-beta.12\BUILD\INSTALL" -D DICE_USE_DOUBLE:BOOL=ON -D NetCDF_DIR:STRING="D:\DICE_RELATION\netCDF4-6-3\netCDF 4.6.3" -D HDF5_DIR:STRING="D:\DICE_RELATION\netCDF4-6-3\netCDF 4.6.3" -D OpenCV_DIR:STRING="D:\packages_build\opencv-3.2.0\BUILD" -D CMAKE_VERBOSE_MAKEFILE:BOOL=OFF -Wno-dev -D DICE_TRILINOS_DIR:FILEPATH="D:\packages_build\build_mvs_trilinos_12-2-2\BUILD\INSTALL" -D CLAPACK_DIR:PATH="D:\packages_build\build_mvs_clapack-3.2.1\BUILD\INSTALL" -G "NMake Makefiles" ..
After executing "do-dice-cmake-win.bat" in cmd, I executed "nmake".
 Ignoring some warning, an error occured.
![33](https://user-images.githubusercontent.com/21332197/57749807-34c5b680-7712-11e9-9895-c69d18968f4e.png)
How can I do in this step? Thank you.

**Comment by dicengine** [comment]
Looks like the path is missing for where netcdf.lib is installed. This would be a CMAKE issue. Try adding a ‘\lib’ to the end of your NetCDF_DIR variable.

On May 14, 2019, at 11:06 PM, dongzi666 <notifications@github.com<mailto:notifications@github.com>> wrote:


There is an error occured in the last step of building DICe. Here is my cmake script
cmake -D CMAKE_BUILD_TYPE:STRING=RELEASE -D DICE_DEBUG_MSG:BOOL=ON -D CMAKE_INSTALL_PREFIX:FILEPATH="D:\packages_build\dice-2.0-beta.12\BUILD\INSTALL" -D DICE_USE_DOUBLE:BOOL=ON -D NetCDF_DIR:STRING="D:\DICE_RELATION\netCDF4-6-3\netCDF 4.6.3" -D HDF5_DIR:STRING="D:\DICE_RELATION\netCDF4-6-3\netCDF 4.6.3" -D OpenCV_DIR:STRING="D:\packages_build\opencv-3.2.0\BUILD" -D CMAKE_VERBOSE_MAKEFILE:BOOL=OFF -Wno-dev -D DICE_TRILINOS_DIR:FILEPATH="D:\packages_build\build_mvs_trilinos_12-2-2\BUILD\INSTALL" -D CLAPACK_DIR:PATH="D:\packages_build\build_mvs_clapack-3.2.1\BUILD\INSTALL" -G "NMake Makefiles" ..
After executing "do-dice-cmake-win.bat" in cmd, I executed "nmake".
Ignoring some warning, an error occured.
[33]<https://user-images.githubusercontent.com/21332197/57749807-34c5b680-7712-11e9-9895-c69d18968f4e.png>
How can I do in this step? Thank you.

**Comment by dongzi666** [comment]
I modified the cmake script as you said. And the cmake script showed below
cmake -D CMAKE_BUILD_TYPE:STRING=RELEASE -D DICE_DEBUG_MSG:BOOL=ON -D CMAKE_INSTALL_PREFIX:FILEPATH="D:\packages_build\dice-2.0-beta.12\BUILD\INSTALL" -D DICE_USE_DOUBLE:BOOL=ON -D NetCDF_DIR:STRING="C:\Program Files\netCDF 4.4.1.1\lib" -D HDF5_DIR:STRING="C:\Program Files\netCDF 4.4.1.1\lib" -D OpenCV_DIR:STRING="D:\packages_build\opencv-3.2.0\BUILD" -D CMAKE_VERBOSE_MAKEFILE:BOOL=OFF -Wno-dev -D DICE_TRILINOS_DIR:FILEPATH="D:\packages_build\build_mvs_trilinos_12-2-2\BUILD\INSTALL" -D CLAPACK_DIR:PATH="D:\packages_build\build_mvs_clapack-3.2.1\BUILD" -G "NMake Makefiles" ..
The error about netcdf.lib is disappeared. When Linking CXX executable ..\bin\DICe_ExoToNetCDF.exe, there were some errors as below
![44](https://user-images.githubusercontent.com/21332197/57790723-e80fc900-776d-11e9-8adb-f16dda7ea14f.png)
How can I do to eliminate the errors? I wish your reply. I appreciated your help all the time.

**Comment by dicengine** [comment]
Looks like you are missing the GLOBAL tools in DICe which need to be enabled. Can you update your cmake script to include -D DICE_ENABLE_GLOBAL:BOOL=ON and try reconfiguring and building again?

**Comment by dongzi666** [comment]
I add  -D DICE_ENABLE_GLOBAL:BOOL=ON to my cmake script. There were errors when linking dicecore.dll.
![55](https://user-images.githubusercontent.com/21332197/57852781-ad15a000-7816-11e9-8a70-ea6142b119c8.png)
After turning DICE_ENABLE_GLOBAL off, dicecore can be built successfully. The error hanpped as last comment.
Any other advice? Thank you again.

**Comment by dicengine** [comment]
From the link line in your picture, it looks like the path is not getting passed through for exodus.lib like the rest of the trilinos libraries. (it only says exodis.lib not <path>\BUILD\INSTALL\lib\exodus.lib) I’m guessing this due to having built trilinos in the last step with exodus off so the CMAKE variables for trilinos are not set correctly.

What happens if you add the location of your trilinos libraries install to the LIBPATH environment variable?

On May 16, 2019, at 6:17 AM, dongzi666 <notifications@github.com<mailto:notifications@github.com>> wrote:


I add -D DICE_ENABLE_GLOBAL:BOOL=ON to my cmake script. There were errors when linking dicecore.dll.
[55]<https://user-images.githubusercontent.com/21332197/57852781-ad15a000-7816-11e9-8a70-ea6142b119c8.png>
After turning DICE_ENABLE_GLOBAL off, dicecore can be built successfully. The error hanpped as last comment.
Any other advice? Thank you again.
