### ISSUE TITLE
Missing best fit plane setting

### ISSUE THREAD

**Issue by shazryz** [dicengine/dice#121]
Hi there,
I'm just wondering why is the best-fit plane in the "Option" bar is missing despite the box is checked? It was there when I first started but somehow, after testing and playing around with the DICe, I can't set up my best-fit plane or treat it as a y-axis for the analysis. Not setting a plane seem to affect the outcome of it, but I can't be 100% sure.

**Comment by dicengine** [comment]
Can you upload a screenshot of this?

**Comment by shazryz** [comment]
![image](https://user-images.githubusercontent.com/50669091/57885947-5c3b8280-77e9-11e9-9c7f-8bfd2a99d3ac.png)

**Comment by shazryz** [comment]
When I first started, the best-fit plane line will appear after I checked the box. I have no idea what happened when I tried to fit it to the image, and the line disappeared from the image when I decreased the image size.

**Comment by dicengine** [comment]
I’ll see if I can re-create the problem to see what’s going on. In the mean time, you can close DICe, delete the best_fit_plane.dat file and re-open DICe, that should reset the best fit plane to it’s original position.

On May 16, 2019, at 2:49 PM, shazryz <notifications@github.com<mailto:notifications@github.com>> wrote:


When I first started, the best-fit plane line will appear after I checked the box. I have no idea what happened when I tried to fit it to the image, and the line disappeared from the image when I decreased the image size.
