### ISSUE TITLE
Stereo DIC issue: Different values for displacements in single camera DIC vs. Stereo

### ISSUE THREAD

**Issue by CaesarTheFox** [dicengine/dice#123]
When I perform 2D DIC on a pipe, the displacement looks correct at all position. But when I try 3D DIC with totally the same images, displacement at certain locations of which the displacement in 2D DIC is not zero become zero. 

Could this be correct? In my understanding, the displacement in pixels are calculated in the same way as 2D DIC, so the displacement in pixels should be totally the same.

**Comment by dicengine** [comment]
Hi Cesar, a couple of questions for you: When you say you use the same images for 2D and 3D I'm not sure I understand. 3D would require stereo image pairs, are you using only the right or the left images for the 2D analysis? The displacement in pixels should the same if you are looking at the DISPLACEMENT_X field or the STEREO_DISPLACEMENT_X (for the right camera), but the MODEL_DISPLACEMENT_X would be the physical displacement in space. You might be seeing zeros for some subsets if the correlation failed. What is the sigma value for the subsets that are changing from reasonable values to zero when you switch from 2D to 3D. Is it -1.0? That would mean that the correlation failed for that subset in stereo.

**Comment by CaesarTheFox** [comment]
I do 2D DIC with the left camera image. So the DISPLACEMENT_X in 2D and 3D DIC should be the same I think. but one is correct and the other is zero. And the sigma value is 0 instead of -1

# point coordinates: 707.000000 201.000000
MODEL_DISPLACEMENT_X,MODEL_DISPLACEMENT_Y,MODEL_DISPLACEMENT_Z,ROTATION_Z,SIGMA,
0.000000,0.000000,0.000000,0.000000,0.000000,
.......
0.000000,0.000000,0.000000,0.000000,0.000000,
all the row is zeros

**Comment by dicengine** [comment]
Are you able to attach your input files and images (one frame for left and right) so I can try to replicate the issue?

On Jun 5, 2019, at 10:14 AM, CaesarTheFox <notifications@github.com<mailto:notifications@github.com>> wrote:


I do 2D DIC with the left camera image. So the DISPLACEMENT_X in 2D and 3D DIC should be the same I think. but one is correct and the other is zero. And the sigma value is 0 instead of -1

point coordinates: 707.000000 201.000000

MODEL_DISPLACEMENT_X,MODEL_DISPLACEMENT_Y,MODEL_DISPLACEMENT_Z,ROTATION_Z,SIGMA,
0.000000,0.000000,0.000000,0.000000,0.000000,
.......
0.000000,0.000000,0.000000,0.000000,0.000000,
all the row is zeros

**Comment by CaesarTheFox** [comment]
Left camera:
![64 8pipe_20190605_152813_001](https://user-images.githubusercontent.com/46268648/58976909-7bae4580-87c0-11e9-9661-2291974db9ca.jpg)
![64 8pipe_20190605_152813_036](https://user-images.githubusercontent.com/46268648/58976921-849f1700-87c0-11e9-8c2b-bd9bbb73c124.jpg)

Right camera:
![64 8pipe_20190605_152737_001](https://user-images.githubusercontent.com/46268648/58976883-6afdcf80-87c0-11e9-8f4f-816725370a2a.jpg)
![64 8pipe_20190605_152737_036](https://user-images.githubusercontent.com/46268648/58976892-718c4700-87c0-11e9-98fa-35d74ae62b7b.jpg)


[input.zip](https://github.com/dicengine/dice/files/3258380/input.zip)

my 3D result for 3 live plot points
![%6Y {L)@TVX1{R{FJDTEI(N](https://user-images.githubusercontent.com/46268648/58977736-3559e600-87c2-11e9-9636-4f5bade443a6.png)
my 2D result
![D@J~0}V{6A~K KAZRD`CCUG](https://user-images.githubusercontent.com/46268648/58977796-56bad200-87c2-11e9-8865-5b79f593cd25.png)

**Comment by CaesarTheFox** [comment]
I guess this is a problem in live plot function because when I open the result in Paraview, I can see many Sigma=-1 at the area near point 1 and 2. But in live plot result sigma=0

**Comment by dicengine** [comment]
Thanks for the additional info. It looks like the utility that post processes the results for the live plots (in DICe_PostProcessor.cpp) looks at the sigma values for a given point's neighbors and if the sigma values are -1, it skips that point (resulting in the default value of 0.0 which is what the array was initialized with). A better option would be to not populate the other fields like DISPLACEMENT, etc. but at least copy the -1.0 into the sigma field. I'll see how much trouble that would be to change. That way you can at least know that the point or points around the live plot point failed. Thanks for pointing this out.

**Comment by dicengine** [comment]
Fixed in commit: fbbb38
