### ISSUE TITLE
What is the algorithm DICe uses for initialization of the left to right camera correlation？

### ISSUE THREAD

**Issue by CaesarTheFox** [dicengine/dice#125]
In the _projective mapping_ part in the reports Triangulation.pdf, I see some about stereo correlation, is stereo correlation to obtain the eight parameters? Or after obtaining these 8 parameters there is other process?

**Comment by dicengine** [comment]
That section of the report is strictly about how the left to right correlation is initialized. Part of the triangulation process (converting two sets of 2d coordinates in the left and right image combined with the camera parameters into 3d model coordinates) involves correlating the pixel location of a point in the left camera with its location in the right camera. To do this DICe uses an eight parameter model for image warping that is applied to the whole image. A minimization procedure is used to determine the eight parameters. This provides an initial guess for getting the pixel coordinates of a point in the right image starting from the left. At that point, a left to right correlation is run for each subset to get more precise correspondences between the left and right camera. Once those are obtained, the triangulation can be executed. After the initial guess is made, the eight parameter warp model is discarded and not used again.

**Comment by CaesarTheFox** [comment]
_At that point, a left to right correlation is run for each subset to get more precise correspondences between the left and right camera._ 

Yes, what kind of algorithm is used in DICe? Grandient-based one in another report? I thought that is for correlation in images from one cameras. Is it also used for correlation in each images pair from two cameras?  I seemed to remember DICe use some correlation method provided in OpenCV. But I forgot which one it is, there are several different methods in OpenCV.

**Comment by dicengine** [comment]
It is the same correlation as is used for single camera correlations. If the user selects GRADIENT_BASED for the optimization algorithm, that is the one that is used, otherwise they can also select GRADIENT_BASED_THEN_SIMPLEX if the cross-correlation is more difficult. Either way it's the same algorithm as is used for correlating in a single camera between frames.

**Comment by CaesarTheFox** [comment]
Thank you very much!
