### ISSUE TITLE
File naming convention for cal images requires the frame number to have same num digits for all frames

### ISSUE THREAD

**Issue by CaesarTheFox** [dicengine/dice#126]
![Q 52VYNVTZ QGK MOL9LE7](https://user-images.githubusercontent.com/46268648/59352457-9a5c9100-8d18-11e9-9e3e-89c045572654.png)

As you can see in the image, I cant select the image I dont want to use in calibration.

And the result compared with the old calibration routine is different. Does the calibration method change?

**Comment by dicengine** [comment]
Are you using Windows? I can't recreate the issue on Mac. I will try Windows later today.

**Comment by CaesarTheFox** [comment]
Yes,I use win10. Thank you in advance.

**Comment by dicengine** [comment]
Were the files ever listed in the select files box? I'm not able to reproduce this error on Windows either. Judging by the large epipolar errors, it seems the calibration failed or the wrong parameters were used. In the old calibration tool, things like the number of dots and where the origin of the dots occurs were automatically detected, but in the current version, the user has to specify these values. I know it seems like the new calibration tool is less automatic, but it has more flexibility. Double check that you have the right values entered for the pattern height/width, etc. There should also be a calibration log file that gets produced. If you can attach that I can look through it to see if there are any indications as to why it failed.

**Comment by CaesarTheFox** [comment]
I try calibration again, but the box is still empty
![)(ZDLN(}T U6Q E806KLTLP](https://user-images.githubusercontent.com/46268648/59466727-eea16700-8e25-11e9-9cb4-e699fac84c57.png)

this is the log file.
[cal.log](https://github.com/dicengine/dice/files/3288071/cal.log)

this is one of the calibration image. So the parameter in pattern option is right if I understand them correctly.
![Calibration_frame_1_0](https://user-images.githubusercontent.com/46268648/59466793-11cc1680-8e26-11e9-978e-c47a511d3335.jpg)

The error is large at certain pair so if I removed them the error would be normal and small I think.

**Comment by dicengine** [comment]
I think the issue is that the file naming convention is that the number of digits in the frame number needs to be the same for all images in the sequence. Could you try using Calibration_00_0.jpg then Calibration_01_0.jpg instead of Calibration_0_0.jpg Calibration_1_0.jpg. That seems to fix the issue for me.

**Comment by dicengine** [comment]
This should probably be fixed in the next version (allowing different digits for frame numbers)

**Comment by CaesarTheFox** [comment]
OK and I find out the reason why the error is too large.
Two cameras are not synchronised. Take the photos of Stopwatch  to check synchrnoisation.
