### ISSUE TITLE
Disable OpenMP for Windows builds

### ISSUE THREAD

**Issue by dtseidl** [dicengine/dice#127]
The Windows DICe binary contained in recent releases uses every available thread on the machine. The current code does not have any OpenMP blocks so this results in a performance hit. 

This can be solved by setting OMP_NUM_THREADS=1 in a terminal before running the dice executable. A better fix would be to compile DICe without OpenMP support. Compiling Trilinos without OpenMP support would achieve this as well as that CMake option is set from the Trilinos build.

**Comment by dicengine** [comment]
I changed the cmake script for windows to address this. I will also rebuild the latest release to turn OpenMP off. 2.0-beta.14 and on will have OpenMP off
