### ISSUE TITLE
Incremental correlation

### ISSUE THREAD

**Issue by marcoalopez** [dicengine/dice#129]
Hello,

I am testing the DICe software for use in a deformation study with ice. In some cases, I have a degradation of the quality of the pattern (not very pronounced) over time and I wonder if there is the possibility of making **incremental correlations** instead. I searched the documentation but found nothing so far.

Thank you in advance,
Marco

**Comment by dtseidl** [comment]
There is an option to perform incremental correlation. You can turn it on by adding the line...

<Parameter name="use_incremental_formulation" type="bool" value="true" />

... in the parms.xml file.

**Comment by marcoalopez** [comment]
Thank you @dtseidl
