### ISSUE TITLE
What is Sigma value in results?

### ISSUE THREAD

**Issue by CaesarTheFox** [dicengine/dice#133]
It is said that Sigma is _predicted std. dev. of the displacement solution given std. dev. of image                     noise and interpolation bias, smaller sigma is better_. I can understand the standard deviation of image. 
But could someone tell me what is exact the standard deviation of the displacement? displacement of pixels? in which direction? or the overall magnitude?
Or is it about model-displacement? which direction?
And there is also an uncertainty in the result. Uncertainty of which result?

**Comment by dicengine** [comment]
Sigma is in terms of pixels, not model displacement. The uncertainty field is very similar to sigma, but includes an additional source of error that comes from the ill-posed problem in DIC, that is the inability to measure displacement in directions orthogonal to image gradients. More details on sigma can be found in Sutton’s DIC book. For the uncertainty field, here is a link to a paper on it: https://link.springer.com/article/10.1007/s11340-017-0360-5

In terms of direction, neither sigma or the uncertainty field is specific to X or Y it applies to both.

On Jul 10, 2019, at 12:53 PM, CaesarTheFox <notifications@github.com<mailto:notifications@github.com>> wrote:


It is said that Sigma is predicted std. dev. of the displacement solution given std. dev. of image noise and interpolation bias, smaller sigma is better. I can understand the standard deviation of image.
But could someone tell me what is exact the standard deviation of the displacement? displacement of pixels? in which direction? or the overall magnitude?
Or is it about model-displacement? which direction?
And there is also an uncertainty in the result. Uncertainty of which result?

**Comment by CaesarTheFox** [comment]
Thank you very much for such a quick and helpful reply！
