### ISSUE TITLE
Enable user to select output fields printed in .txt output files from GUI

### ISSUE THREAD

**Issue by cbm30** [dicengine/dice#134]
Hi,

After running a stereo correlation, the ouput text files are missing some columns like 'NORMAL_STRAIN_X' and '_Y' which are included in the .e file. In terms of strain, only the VSG strains are outputted to the .txt files. Is there a way for this data to be exported to the .txt files?

Thanks,
Chris

**Comment by dicengine** [comment]
It seems like a good idea to add a way for the user to select in the GUI which fields end up in the .txt output files. We'll see how easy it would be to include that option in a future version of the GUI. For the time being, if you want to run the executable from the command line, you can add a parameter block to the params.xml file that will enable you to select which fields are output in the .txt file:

  <ParameterList name="output_spec">
    <Parameter name="NORMAL_STRAIN_X" type="bool" value="true" />
    <Parameter name="NORMAL_STRAIN_Y" type="bool" value="true" />
    <Parameter name="COORDINATE_X" type="bool" value="true" />
    <Parameter name="COORDINATE_Y" type="bool" value="true" />
    <Parameter name="DISPLACEMENT_X" type="bool" value="true" />
    <Parameter name="DISPLACEMENT_Y" type="bool" value="true" />
    <Parameter name="VSG_STRAIN_XX" type="bool" value="true" />
    <Parameter name="VSG_STRAIN_YY" type="bool" value="true" />
    <Parameter name="VSG_STRAIN_XY" type="bool" value="true" />
  </ParameterList>

Note that if you modify the params.xml file and try to run DICe again from the GUI (not the command line) the params.xml file will get overwritten removing your changes.

**Comment by cbm30** [comment]
Thanks! This resolved the issue.

Best,
Chris
