### ISSUE TITLE
DICe can not be installed on disk D:/

### ISSUE THREAD

**Issue by anliangw** [dicengine/dice#148]
I install DICe_setup_v2.0-beta.15-win32-x64.exe on my disk D:\Program Files (x86)\Digital Image Correlation Engine. When I open it, there appears error "Error! invalid DICe executable: C:\Program Files (x86)\Digital Image Correlation Engine\dice.exe". I alternatively install it on D, then it works well.
I was wondering that the installation must be on C:/ ?

**Comment by dicengine** [comment]
This occurs when a bad path gets saved in the .dice.js file in your home directory for the working_directory variable. Changing to a new drive (D:/) inadvertently fixed this somehow (likely since there probably wasn't a .dice.js file in the home directory on D:/. This issue has been fixed in a recent commit, but has not been released in a new installer. The next DICe installer (version 16) will have the fix for this issue. If you would like to install DICe on C:/, simply delete the .dice.js file in your home directory on C:/ and try installing DICe again.

**Comment by l13r** [comment]
I'm trying to work with DICe installer (version 15). I got the same error and I deleted the .dice.js file. When I open DICe, the error no longer appears, but when I try to run my stereo analysis, a similar error appears: "DICe execution failed: invalid executable: C:\Program Files (x86)\Digital Image Correlation Engine\dice.exe". I have tried to install in D but I get the same error. Any ideas to solve this problem? When will version 16 be available? Thanks.

**Comment by dicengine** [comment]
Open the .dice.js file in your home directory and see if the path listed for the working directory is valid. If not, change it to a valid working directory or again delete the .dice.js file and try again

**Comment by l13r** [comment]
The path listed for the working directory is valid. Every time I close the program, the .dice.js file is created again and the path is ok. I try to delete the .dice.js file and open DICe again but when I run the stereo analysis, the error appears again. I tried to install DICe in the default folder but I could not eliminate the error.

**Comment by dicengine** [comment]
looks like the default execution path for the DICe install is hard coded for the C:\ drive. If you add a line to your .dice.js file:

var execPathOverride = "<path to folder containing dice.exe on D:>"

The GUI should find the executable

**Comment by l13r** [comment]
I installed DICe in the default folder in C:\ and the path to folder containing dice.exe is located in C:\Program Files (x86)\Digital Image Correlation Engine. I have added the line you told me whit this path, but the error appears again. GUI starts correctly but when I try to run stereo analysis, this window pops up.

![image](https://user-images.githubusercontent.com/58216876/69981250-3b8f0c00-1532-11ea-9a88-9382020ebeb5.png)

**Comment by dicengine** [comment]
Is there any output in the console window at the bottom?

**Comment by l13r** [comment]
After loading all images and cal file, the next message appears: 
_---Correlation parameters read successfully---
---List of images constructed successfuly---
Unknown exception_
I alternatively have deleted all DICe files and I have installed the previous version (Version 2.0-beta.14). At the moment it seems that this version works correctly. I will try to work with this until the next version. Thanks.
