### ISSUE TITLE
output the displacement gradient (du/dx, du/dy, dv/dx, dv/dy) 

### ISSUE THREAD

**Issue by anliangw** [dicengine/dice#149]
I am using DICe to investigate the deformation of sea ice.  I need to output the displacement gradient (du/dx, du/dy, dv/dx, dv/dy)  to compare the Green strain and Cauchy strain. Could you give me a guide on how to output those parameters?

**Comment by dicengine** [comment]
Currently, there isn't a way to do this from the GUI, you have to modify the params.xml file and run DICe from the command line using "<path to dice exec>\dice -i input.xml -v". If you change the params.xml file and run the DICe executable from the GUI, it will overwrite the params.xml file removing your edits.

In the params.xml file output spec add a parameter for the VSG_DUDX, etc as follows:

  <ParameterList name="output_spec">
    <Parameter name="COORDINATE_X" type="bool" value="true" />
    <Parameter name="COORDINATE_Y" type="bool" value="true" />
    <Parameter name="DISPLACEMENT_X" type="bool" value="true" />
    <Parameter name="DISPLACEMENT_Y" type="bool" value="true" />
    <Parameter name="VSG_STRAIN_XX" type="bool" value="true" />
    <Parameter name="VSG_STRAIN_YY" type="bool" value="true" />
    <Parameter name="VSG_STRAIN_XY" type="bool" value="true" />
    <Parameter name="GAMMA" type="bool" value="true" />
    <Parameter name="MATCH" type="bool" value="true" />

    <Parameter name="VSG_DUDX" type="bool" value="true" />

  </ParameterList>

You can do the same for VSG_DUDY, etc.
