### ISSUE TITLE
Buidling DICe with Global Flag issue

### ISSUE THREAD

**Issue by sleach3** [dicengine/dice#151]
I am trying to build DICe again on a Jetson but with the Global flag on. I am using this make file:
`
rm -f CMakeCache.txt
rm -rf CMakeFiles

cmake \
 -D CMAKE_BUILD_TYPE=RELEASE \
 -D DICE_TRILINOS_DIR=/home/Clay/Builds/trilinos/build/install \
 -D CMAKE_INSTALL_PREFIX:FILEPATH=/usr/local \
 -D CMAKE_VERBOSE_MAKEFILE:BOOL=ON \
 -D DICE_DEBUG_MSG:BOOL=OFF \
 -D DICE_USE_DOUBLE:BOOL=ON \
 -D TIFF_DIR:FILE_PATH=/usr/lib/aarch64-linux-gnu/ \
 -D JPEG_DIR:FILE_PATH=/usr/lib/aarch64-linux-gnu/ \
 -D PNG_DIR:FILE_PATH=/usr/lib/aarch64-linux-gnu/ \
 -D CMAKE_CXX_FLAGS:STRING="-Wall" \
 -D DICE_USE_EPETRA:BOOL=ON \
 -D DICE_ENABLE_MANYCORE:BOOL=OFF \
 -D DICE_ENABLE_GLOBAL:BOOL=ON \
 $EXTRA_ARGS ../
`

When building I receive the following error:

`../../lib/libdicecore.a(DICe_ImageSerial.cpp.o): In function `DICe::Image::update_image_fields(char const*, Teuchos::RCP<Teuchos::ParameterList> const&)':
DICe_ImageSerial.cpp:(.text+0x4f4): undefined reference to `DICe::utils::read_image(char const*, double*, Teuchos::RCP<Teuchos::ParameterList> const&)'
../../lib/libdicecore.a(DICe_ImageSerial.cpp.o): In function `DICe::Image::Image(char const*, Teuchos::RCP<Teuchos::ParameterList> const&)':
DICe_ImageSerial.cpp:(.text+0x72b8): undefined reference to `DICe::utils::read_image(char const*, double*, Teuchos::RCP<Teuchos::ParameterList> const&)'
../../lib/libdicecore.a(DICe_ImageSerial.cpp.o): In function `DICe::Image::Image(char const*, int, int, int, int, Teuchos::RCP<Teuchos::ParameterList> const&)':
DICe_ImageSerial.cpp:(.text+0x82d8): undefined reference to `DICe::utils::read_image(char const*, double*, Teuchos::RCP<Teuchos::ParameterList> const&)'
../../lib/libdicecore.a(DICe_Image.cpp.o): In function `DICe::Image::write(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
DICe_Image.cpp:(.text+0x1024): undefined reference to `DICe::utils::write_image(char const*, int, int, double*, bool)'
../../lib/libdicecore.a(DICe_Image.cpp.o): In function `DICe::Image::write_overlap_image(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, Teuchos::RCP<DICe::Image>)':
DICe_Image.cpp:(.text+0x12a0): undefined reference to `DICe::utils::write_color_overlap_image(char const*, int, int, double*, double*)'
../../lib/libdicecore.a(DICe_Image.cpp.o): In function `DICe::Image::write_grad_x(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
DICe_Image.cpp:(.text+0x1684): undefined reference to `DICe::utils::write_image(char const*, int, int, double*, bool)'
../../lib/libdicecore.a(DICe_Image.cpp.o): In function `DICe::Image::write_grad_y(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
DICe_Image.cpp:(.text+0x18cc): undefined reference to `DICe::utils::write_image(char const*, int, int, double*, bool)'
../../lib/libdicecore.a(DICe_Subset.cpp.o): In function `DICe::Subset::write_subset_on_image(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, Teuchos::RCP<DICe::Image>, Teuchos::RCP<DICe::Local_Shape_Function>)':
DICe_Subset.cpp:(.text+0x7cc): undefined reference to `DICe::utils::write_image(char const*, int, int, double*, bool)'
../../lib/libdicecore.a(DICe_Subset.cpp.o): In function `DICe::Subset::write_tiff(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)':
DICe_Subset.cpp:(.text+0xb44): undefined reference to `DICe::utils::write_image(char const*, int, int, double*, bool)'
collect2: error: ld returned 1 exit status
src/core/CMakeFiles/dice_strain.dir/build.make:147: recipe for target 'bin/dice_strain' failed
make[2]: *** [bin/dice_strain] Error 1
CMakeFiles/Makefile2:184: recipe for target 'src/core/CMakeFiles/dice_strain.dir/all' failed
make[1]: *** [src/core/CMakeFiles/dice_strain.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
`
This error seems to be similar to issue #136 I believe but I have not been able to track down how to best fix it.

**Comment by dicengine** [comment]
with the changes to the configuration, you will need to clean your existing build by running $make clean from the command line to get rid of the old utils build.
