### ISSUE TITLE
Quadratic shape function failed

### ISSUE THREAD

**Issue by cslayers** [dicengine/dice#155]
I tried to use the quadratic shape function by adding the following line to the config file params.xml 
`<Parameter name="shape_function_type" type="string" value="QUADRATIC" /> `
according to the template xml file generated by 
`dice -g template`
but the command line program dice return the error message like

> Error!  An attempt was made to access parameter "shape_function_type" of type "string"
> in the parameter (sub)list "Schema_Correlation_Parameters"
> using the incorrect type "enum DICe::Shape_Function_Type"!
> 
> Throw number = 1

And then I set the shape function to the affine shape function, it also failed with the same error message.
`<Parameter name="shape_function_type" type="string" value="AFFINE" /> `

**Comment by dicengine** [comment]
i just pushed a commit that fixes this: https://github.com/dicengine/dice/commit/fcb11ca72bbbfe791dae57fc96c76f302c148aa8
