### ISSUE TITLE
a possible error in GRADIENT-BASED LOCAL DIC FORMULATION

### ISSUE THREAD

**Issue by dongzi666** [dicengine/dice#157]
I read the GRADIENT-BASED LOCAL DIC FORMULATION in Report No. SAND2016-7360 R, which is in dice/report file. inv(R) in Equation (18) may be [cos_theta, sin_theta; -sin_theta, cos_theta] rather than  [cos_theta, -sin_theta; sin_theta, cos_theta]. If so, the relevant code in DICe_LocalShapeFunction.cpp should be corrected. 
The relevant code is "Gx = use_ref_grads ? cosTheta*gx - sinTheta*gy : gx; Gy = use_ref_grads ? sinTheta*gx + cosTheta*gy : gy;"

check it, thank you.

**Comment by dicengine** [comment]
I double checked that the code matches the document notation. I think the confusion may be in the way you define the rotation angle (right hand rule or left hand rule).

**Comment by dongzi666** [comment]
Thank you for your reply.
I don't think I made myself clear.

Your conde matches your report.

Is the code ("Gx = use_ref_grads ? cosThetagx - sinThetagy : gx; Gy = use_ref_grads ? sinThetagx + cosThetagy : gy;" ) obtained from the equation (19) in Report No. SAND2016-7360 R ? 

My confusion is that the ratation matrix (equation 2) and inverse of that matrix (equation 18) are same in the report. I did check it in matlab and found it's wrong.

**Comment by dicengine** [comment]
Looks like you're right. Eq 18 is correct but the signs on the sin()s in equation 2 should be switched. The positive direction for rotations in DICe is clockwise (which is standard for image processing, but not for mechanics which is where eq 2 comes from). Ultimately, since only eq 18 is implemented in DICe, not eq 2, the code is correct according to the rotation convention.

**Comment by dongzi666** [comment]
another ask. Could you provide more information reports about the technique you used in DICe ?
And did you do all the software work ( both DICe and DICe_gui ) by yourself? It's really  a great work.
you constructed some complex class, and schema class confused me. Could you provide more description document to let me understand the detail of the codes?

**Comment by dicengine** [comment]
I wish we had more documentation on the code itself, but aside from the doxygen documentation in the code comments, that's all we have. Was there something specific you were confused by?

**Comment by dongzi666** [comment]
I have used "VS2013 x64 Native Tools Command Prompt" to build the the DICe source successfully in windows 7 based on your building windows step in doucument. However I don't know how to debug. Please tell a way to debug in windows.
