### ISSUE TITLE
PostProcessor : Neighbourhood list search minor modifications

### ISSUE THREAD

**Issue by dandefou** [dicengine/dice#162]
In order to continue the discussion from the issue #161 about the neighbourhood list search, in which the strain_window_size changes units when running a 2D (pixels) or a stereo (physical units), some small modifications could be done:

1. Change the variable name from `strain_window_size_in_pixels` to only `strain_window_size`. 
2. Transform this variable from **int** to **double**, in order to take into account physical sizes with decimal values. 
3. I propose to change the line to: `TEUCHOS_TEST_FOR_EXCEPTION(window_size_==0,std::runtime_error,"Error, window size must be different than 0");` in order to allow the k-nearest search.  https://github.com/dicengine/dice/blob/9f4f06cee03b1ca76f7bf3cf8adca1f7b6fe06b5/src/core/DICe_PostProcessor.cpp#L250 
4. This division should be done only in the _radius search_ (line 200), or the value multiplied by -2.0 at the line 175 for the _k-nearest search_ https://github.com/dicengine/dice/blob/9f4f06cee03b1ca76f7bf3cf8adca1f7b6fe06b5/src/core/DICe_PostProcessor.cpp#L258

Thanks.

**Comment by dicengine** [comment]
The cleanest way to deal with the strain_window_size_in_pixels issue was to keep the size in pixels for both 2D and stereo. In stereo, the subset coordinates in the left image are used to determine the neighbors. The physical coordinates in model space are used for the VSG strain values, but the neighborhoods are initialized based on the pixel coordinates.

The suggested changes to items 3 and 4 were added to https://github.com/dicengine/dice/commit/cd9b944a9c9e1ae57606e0e505269a6659d09e70
