### ISSUE TITLE
2D calibration failed 

### ISSUE THREAD

**Issue by Ra-ux-ops** [dicengine/dice#167]
Hi,

I have been trying to do a 2D calibration on both windows and Mac computers. It however keeps failing. Looking at the windows Log file nothing special seems to be going on. I have tried many different things like changing the file type from .JPEG to .Tiff and vice versa. The software is able to recognize most positions of the calibration pattern correctly, but still fails at the end. On windows the only error that occurs is  Dice cal execution failed (see cal.log for details)
![dice_windows_calibration_settings](https://user-images.githubusercontent.com/60887192/80796252-05b48900-8b9f-11ea-98b3-62082a253f91.JPG)

[cal.log](https://github.com/dicengine/dice/files/4563193/cal.log)

On mac i tried calibrating with the same images with no luck. With the first attempt I got the exact same log as on windows.
[Mac log.log](https://github.com/dicengine/dice/files/4563219/Mac.log.log)

For the seccond attempt I tried to calibrate with 4 of the same images. This time it gave the following error:

Calibration::calibrate(): performing OpenCV calibration
libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: /Users/dzturne/code/KDICe/src/opencv/DICe_Calibration.cpp:288:

Throw number = 1

Throw test that evaluated to true: pose_estimation_index_>=(int_t)num_images()

error, invalid pose estimation index

[Mac log 2.log](https://github.com/dicengine/dice/files/4563232/Mac.log.2.log)

This folder contains the images that I used:

[Cal_test.zip](https://github.com/dicengine/dice/files/4563240/Cal_test.zip)

At this point I do not know what to do anymore to get the calibration to work.

**Comment by dicengine** [comment]
My guess is that there could be a bug in the pose estimation index in that it might not offset if the first frame is not at zero (but at 6315 in your case). Try making the post estimation index 0 and see what happens. If that works, I'll convert this to a bug issue.

**Comment by Ra-ux-ops** [comment]
I changed the numbers from 6315 to 0 and changed the post estimation to 0 as well. The OpenCv calibration at the end takes a little bit longer to finish, but I still end up getting the same error

[Cal_files.zip](https://github.com/dicengine/dice/files/4564017/Cal_files.zip)

**Comment by bvanmieg** [comment]
Hi Ra-ux-ops,

The images you sent in you first post are not the same as the ones you show in the post. The filenames are different and the calibration target is different. It also even seems as if the images are 4 times identical. Nevertheless, I tried to correlate and get the same error (Win10 machine).
I noticed however as well that the images are huge (> 20MB each).
I renamed the files to start at zero, same error?

I reduced the image size (1/2 of the original size): same error.
I reduced the images size (1/4 of the original size): calibration succesfull

I noticed the same error a while ago in one of the previous posts....

[cal.log](https://github.com/dicengine/dice/files/4564114/cal.log)
[cal_target.txt](https://github.com/dicengine/dice/files/4564119/cal_target.txt)
[cal_input.txt](https://github.com/dicengine/dice/files/4564122/cal_input.txt)
![CAL_LEFT](https://user-images.githubusercontent.com/31392341/80805244-ce9ea180-8bb7-11ea-843f-3bff29dc86fc.png)

**Comment by Ra-ux-ops** [comment]
The photos were made with a DSLR. I tried reducing the image size in paint to 1/4 of it's original size but it still fails. 
[final direct2.zip](https://github.com/dicengine/dice/files/4564387/final.direct2.zip)
[Cal_test_pictures.zip](https://github.com/dicengine/dice/files/4564398/Cal_test_pictures.zip)

**Comment by bvanmieg** [comment]
Ra-uw-ops,
There are normally no additional steps besides downloading the .exe and installing it.

I tried with your new pictures and it does indeed not work.
What surprized me was that the size of the images is the same as mine but the horizontal/vertical resolution is not the same. The initial resolution was 240dpi and after reducing is to 25% you still have 120dpi left. In my case I have 96dpi left.

Can you try with the images I resized?
[CAL.zip](https://github.com/dicengine/dice/files/4565922/CAL.zip)

**Comment by Ra-ux-ops** [comment]
It has worked for this occurrence, thanks! However I tried to calibrate with a few different pictures (reduced image size to 96 dpi) and it keeps giving me the following message:
DICe cal execution failed (see cal.log for details).
[Cal_pictures.zip](https://github.com/dicengine/dice/files/4567406/Cal_pictures.zip)
[Cal_files.zip](https://github.com/dicengine/dice/files/4567402/Cal_files.zip)

In the cal.log and nothing strange seems to be going on. Furthermore, in the cal (xml-file)  it was able to determine the R11-R33 coordinates. I am trying to get a procedure because up until now the calibration seems to be not working when trying the same steps as suggested.

**Comment by Ra-ux-ops** [comment]
Hi,

I would like to report back on the issue.
There is indeed a bug with the pose estimation frame when the image name does not start at 0, that is fixed by setting it to 0 again. Otherwhise the openCV calibration does not run.
Furthermore, I have a question about the local displacement (2D-DIC displacement), namely is there any way to convert the displacement values in pixels to for example mm

**Comment by dicengine** [comment]
I just pushed a commit to the GUI https://github.com/dicengine/dicegui/commit/f63abe7f12822eea645d53c2d19b85136e328c5f
that should address the pose estimation frame indexing issue.

If the 2D analysis is calibrated there will be output fields created in model coordinates at whatever scale the calibration is at. These fields should be labeled MODEL_COORDINATES.
