### ISSUE TITLE
Make Install seems to delete dice executable and fails on Ubuntu18

### ISSUE THREAD

**Issue by bsnow31** [dicengine/dice#172]
Hello,
I am trying to install DICe in Ubuntu18 and am getting close to the end but the install fails because the bin/dice/ directory isn't created. I have successfully installed Trilinos and OpenCV. Here is the end of the output when the error occurs:

$make all install
... [0-99% Built other stuff]
[100%] Built target custom_app_example
Install the project...
-- Install configuration: "RELEASE"
-- Up-to-date: /~/DICe/build/include/DICe.h
... (A lot of things are Up-to-date)
-- Up-to-date: /~/DICe/build/include/DICe_OpenCVServerUtils.h
CMake Error at src/core/cmake_install.cmake:55 (file):
  file INSTALL cannot find "/~/DICe/build/bin/dice".
Call Stack (most recent call first):
  src/cmake_install.cmake:98 (include)
  cmake_install.cmake:42 (include)

Makefile:117: recipe for target 'install' failed
make: *** [install] Error 1

I have edited the build.make files to include the proper directory to liblapack.so.3 and libblas.so.3, but I am not sure if that would cause this error. Any help would be greatly appreciated.
Thanks

**Comment by dicengine** [comment]
Have you checked that /~/DICe/build/bin/ exists and that the DICe executables that get built with the make command are in there? Looks to me like when you build DICe, it's putting the libraries and executables in a non-standard location so that the INSTALL step can't find them.

**Comment by bsnow31** [comment]
Yes, ~/DICe/build/bin/ exists and has 8 executables in it (DICe_Cal, DICe_CineStat ... DICe_TrackingMovieMaker) but no DICe/bin/dice.

**Comment by dicengine** [comment]
There should be an executable called "dice" in there, if not, it either wasn't built or was put somewhere else for some reason. That's the main executable for DICe.

**Comment by bsnow31** [comment]
It looks like bin/dice is created when it builds dice_main (I saw the file was created) but then it is deleted during the "Built target custom_app_example" stage. Any idea why that would happen?

**Comment by dicengine** [comment]
That's really weird...as an experiment, you could disable the custom app example by commenting out using hashtags everything after about line 37 in DICe/tests/examples/CMakeLists.txt  (it's not really needed for anything except to serve as an example for how to build your own DIC app using DICe).

**Comment by bsnow31** [comment]
That did not work. I think dice is actually deleted in the install step (i was just judging it based on when I saw the file disappear, so I could have been wrong). I re-ran make install but quit it after bin/dice was created (and before it was deleted) and now I am able to run the examples (getting identical results) and it passed 99% of the tests even though it didn't technically complete the install. So, it seams to still work even with that strange error. Should I be worried about it missing functionality and try to fix this to get an install without an error or just go with it? I plan to use dice to do 2D image correlation on some video (kind of like the mechanism example).

**Comment by dicengine** [comment]
If the executables are there, you're all set. The only thing the install step should do is move these to another folder specified in your cmake script. There shouldn't be any missing functionality.

**Comment by bsnow31** [comment]
Ok Great, I will work with what I've got then. Thank You for your help!
