### ISSUE TITLE
Stereo calibration failure while preview is good due to poor lens distortion model

### ISSUE THREAD

**Issue by Wei-Meng515** [dicengine/dice#174]
Hi everyone,

I am a new learner on DICe and working on 3D calibration. I got an error reported "DICe cal execution failed". The cal.log is attached as following. 

[cal.log](https://github.com/dicengine/dice/files/4789194/cal.log)

It looks like the program stopped by itself for some unknown reasons.

For testing, I only included three pairs of images and checked them in the preview window. 
![cal_left](https://user-images.githubusercontent.com/52252239/84830377-ed81b780-afee-11ea-9af1-2943f3c650d9.png)
![cal_right](https://user-images.githubusercontent.com/52252239/84830419-f4a8c580-afee-11ea-930c-717f487d9c36.png)

All of them look good in preview, but if I run the calibration I got the "DICe cal execution failed" error.

I attached the three pairs of my calibration images as following.

[cali_crop.zip](https://github.com/dicengine/dice/files/4789220/cali_crop.zip)

The parameters I used are attached as (converted from xml to txt for uploading):
[cal_input.txt](https://github.com/dicengine/dice/files/4789230/cal_input.txt)

Any suggestions would be highly appreciated!

Thanks in advance.

**Comment by dicengine** [comment]
what happens if you change the cal_origin_x and _y to 4 instead of 3?

**Comment by Wei-Meng515** [comment]
> what happens if you change the cal_origin_x and _y to 4 instead of 3?

If I change the origin offset from (3,3) to (4,4) the target will be mismatched. It looks like this
![cal_left](https://user-images.githubusercontent.com/52252239/84833527-16a54680-aff5-11ea-95de-f8e5ff253fd8.png)
![cal_right](https://user-images.githubusercontent.com/52252239/84833532-1a38cd80-aff5-11ea-989b-d24a7e126131.png)

**Comment by Wei-Meng515** [comment]
> what happens if you change the cal_origin_x and _y to 4 instead of 3?

I think the reason is I cropped the image. The resolution of the two images are different. I used the original images and programmed does not stop automatically. But I still got  an error said "DICe cal execution failed".  My problem is very similar to the issue #168 , so I just replied there.

Any suggestion would be highly appreciated!

Thank you!

**Comment by dicengine** [comment]
can you post a set of 3-5 non-cropped images so I can debug. I added a similar comment to issue #168

**Comment by dicengine** [comment]
For this particular example, the lens distortion model in opencv isn't a good match for the lens distortions in the images above. The calibration routine has been updated in https://github.com/dicengine/dice/releases/tag/v2.0-beta.16 to not fail for a poor lens distortion model, but throw a warning instead.

**Comment by bbellster** [comment]
Hi, I'm not sure whether I have the same issue or not, but I am unable to calibrate my stereo setup. I've attached representative images. The log file is very sparse:
** Digital Image Correlation Engine (DICe)
** v2.0
** git: v2.0-beta.16
** MPI: disabled
** Manycore: disabled
** Data type: double
** Copyright 2015 National Technology & Engineering Solutions of Sandia, LLC (NTESS)
** Report bugs and feature requests as issues at https://github.com/dicengine/dice


DICe_Cal begin

input file:  C:\Users\30706450\dice_working_dir\results\cal_input.xml
output file: C:\Users\30706450\dice_working_dir\results\cal.xml

![left_13](https://user-images.githubusercontent.com/6289383/85743888-ab790580-b6c1-11ea-8ba5-0e88c95aff03.png)
![right_14](https://user-images.githubusercontent.com/6289383/85743896-acaa3280-b6c1-11ea-9281-6bc9f91c3961.png)

**Comment by bvanmieg** [comment]
Hi bbellster,

The treshold value for you first image seems to be acceptable but not for you second image.
Try to disable auto treshold and modify manually the threshold constant.
If you want I can try as well, but then you need to provide the images (and not the thresholded one's).

Bart

**Comment by bbellster** [comment]
Hi again, 
Can someone please try calibrating with these images? The calibrator seems to find intersection points in the preview, but calibration fails.  Nothing seems to work for me...

Brett

**Comment by bvanmieg** [comment]
Hi Brett,

Can you share your original calibration images?
I cannot use the images you provided in: https://github.com/dicengine/dice/issues/174#issuecomment-649601760

Regards,
Bart

**Comment by bbellster** [comment]
I thought that I had uploaded them, must have failed.


[pairs.zip](https://github.com/dicengine/dice/files/4848283/pairs.zip)

mages.

**Comment by bvanmieg** [comment]
I used the installer of Version 2.0-beta.15 (because the GUI has problems in version 16, not related to your issue) and the calibration goes perfectly fine. I left all calibration settings and threshold as default and used a pattern of  14 x 10.

input and output files attached
[results.zip](https://github.com/dicengine/dice/files/4848588/results.zip)

**Comment by bbellster** [comment]
I installed 2.0.15 on my windows 10 machine and I'm getting the same error:
C:\Users\dzturne\Software\trilinos\packages\teuchos\parameterlist\src\Teuchos_XMLParser.cpp:538:

Throw number = 1

Throw test that evaluated to true: 1

XML parse error at line 4: reference not well-formed: expected name or '#'

**Comment by bbellster** [comment]
I have figured out that this must be some kind of file referencing issue. I think that it has something to do with the path to the working directory. notice above that the error above is referencing Users\dzturne\.... That is not my username on my PC and I have no idea where that is coming from. Is this the GUI issue that you were referring to previously?

**Comment by dicengine** [comment]
I double checked that the calibration tool works for the images above in version 2.0-beta.16. My guess is that there is a non-numeric character in the path to where you placed the calibration images. For example I know that Chinese characters in a path will not get parsed correctly. The same is true for accents.

The Users/dzturne references in the error are because that is the path on the machine I used to build the binary installers. You can ignore this.
