### ISSUE TITLE
Stereo left and right suffix not being added to input file when generated with GUI for v2.0-beta.16

### ISSUE THREAD

**Issue by bvanmieg** [dicengine/dice#175]
Hi,

I was trying DICE 2.0-beta.16 with the latest source code of the DICE_GUI and faced following error during stereo correlation:

[DICe_DEBUG]: read_image_dimensions(): (opencv) file name: /home/bvm/TEST/DICE_V16//TEST2_0000.tiff
[DICe_DEBUG]: [PROC 0] Decomp::populate_coordinate_vectors(): image width:  0
[DICe_DEBUG]: [PROC 0] Decomp::populate_coordinate_vectors(): image height: 0

 I get the same error when running from the terminal as when running in GUI.

When looking at the input.xml (created with the GUI), the image path is not correct (double slash) and although this is a stereo correlation, the left and right suffix are missing in the input.xml file....
[input.txt](https://github.com/dicengine/dice/files/4810340/input.txt)

The program works fine from terminal with following (own-created) input file:
[input2.txt](https://github.com/dicengine/dice/files/4810346/input2.txt)

Regards,
Bart

**Comment by dicengine** [comment]
Thanks for the heads up. I’ll fix this when I get back to the office in a couple weeks.  -Dan

On Jun 21, 2020, at 4:11 PM, bvanmieg <notifications@github.com> wrote:

﻿

Hi,

I was trying DICE 2.0-beta.16 with the latest source code of the DICE_GUI and faced following error during stereo correlation:

[DICe_DEBUG]: read_image_dimensions(): (opencv) file name: /home/bvm/TEST/DICE_V16//TEST2_0000.tiff
[DICe_DEBUG]: [PROC 0] Decomp::populate_coordinate_vectors(): image width: 0
[DICe_DEBUG]: [PROC 0] Decomp::populate_coordinate_vectors(): image height: 0

I get the same error when running from the terminal as when running in GUI.

When looking at the input.xml (created with the GUI), the image path is not correct (double slash) and although this is a stereo correlation, the left and right suffix are missing in the input.xml file....
input.txt<https://github.com/dicengine/dice/files/4810340/input.txt>

The program works fine from terminal with following (own-created) input file:
input2.txt<https://github.com/dicengine/dice/files/4810346/input2.txt>

Regards,
Bart

**Comment by dicengine** [comment]
This should now be fixed with commit: https://github.com/dicengine/dicegui/commit/232c32823caade92ad035f04d46ad11122c954d3

I rebuilt the installers for version 16 with this fix on the releases page.

**Comment by bvanmieg** [comment]
I tried by rebuilding the GUI and it solved indeed the issue.
Did not check the installer yet, but assume this can be closed.
Thanks Dan!
