### ISSUE TITLE
Dice execution failed due to SSSIG threshold being set too high

### ISSUE THREAD

**Issue by Hustben** [dicengine/dice#180]
Hi, in 2D-DIC module, when used subset-based full-field analysis mode, after load reference image and deformed image, click the preview sssig mask button and the bug appears. But it works in global mode. whats the reason.
![DICe](https://user-images.githubusercontent.com/54845149/88259256-84c7e200-ccf4-11ea-8fa5-858cf4f133ca.png)

**Comment by Hustben** [comment]
Hi DICe team,
  This problem still did not solve, why is this happening. Looking forward to your reply.
  Thanks.

**Comment by dicengine** [comment]
It's likely that your SSSIG threshold is too high. Try 0 and see what happens. The SSSIG threshold measures the amount of gradients in the image near the subset locations. If there isn't enough gradient information, getting a quality DIC result is difficult.

**Comment by Hustben** [comment]
Setting the SSG threshold to 0, and the problem have been solved. Thank you very much for your help.
