### ISSUE TITLE
binary files

### ISSUE THREAD

**Issue by czb** [dicengine/dice#19]
Hi,

could you please include Win32 or Win64 binaries with MPI enabled into the release section of Github? That would significantly speed up the learning process of your great DIC engine.

Best regards,
Oldrich

**Comment by dicengine** [comment]
Hi Oldrich,

Thanks, you’re right. The binaries will be included with the official release of v1.0 which will take place in April 2015 (as well as package installers for Linux and Mac). They will be posted to github as soon as the release testing is finished, which may be before April.

Regards,
Dan



On Dec 7, 2015, at 9:14 AM, Oldrich Svec <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,

could you please include Win32 or Win64 binaries with MPI enabled into the release section of Github? That would significantly speed up the learning process of your great DIC engine.

Best regards,
Oldrich

**Comment by dicengine** [comment]
The package installers for windows (64bit) with and without MPI enabled have been released as a beta version. Threading is not enabled for these versions.
