### ISSUE TITLE
Defining pixel size

### ISSUE THREAD

**Issue by evgenabaqus** [dicengine/dice#190]
Hello DICe developers,

Thank you very much for the Software. 

I'm exploring 2D analysis using DICe, It works very well, 
however, there is one small thing that I can't understand how to solve.

Firstly, I perform camera calibration using point grid 12x9 with spacing 3.5mm
after that I load images and run 2d analysis, then import results in Paraview. 

In Paraview I want to see displacement field, 
however results in terms of pixels.

Where in DICe I can set value which is defining size of one pixel?
I went trough calibration file but didn't find any information about pixel size.

Could you please help to resolve this small issue?

I use DICe_setup_v2.0-beta.16-win32-x64.exe

Thanks,
EV

**Comment by dicengine** [comment]
Hi EV,

I'm a little confused by what you are trying to achieve. I get the impression that you simply want to view the physical displacement field in terms of physical units not the image displacement field which is in units of pixels. The image displacements are in a field called SUBSET_DISPLACEMENTS, the physical displacements are in a field called MODEL_DISPLACEMENTS. Check if you have both of these in your output file and choose the right one depending on whether you want to see pixel units or physical units.

-Dan

**Comment by mpaes15** [comment]
Hi Dan, this option "MODEL DISPLACEMENT" is not available in version 3 beta 6.

**Comment by dicengine** [comment]
MODEL_DISPLACEMENT_X, ..._Y, and ..._Z are fields and they are output in the exodusII files in version 3.0-beta.6. If you would like to output them in the .txt files you have to add them to the output spec.
