### ISSUE TITLE
Any advice on learning the code?

### ISSUE THREAD

**Issue by SampanLee** [dicengine/dice#200]
Hi DICe developers,
    Thank you very much for the open-source code.
     I want to learn the source code of DICe, but I find that the code is very complex. Thus, I wonder  if there is any advice on how to study the source code?
Thanks,
Sam

**Comment by dicengine** [comment]
We don't have any code-related documentation currently, but if you have something specific you are trying to do I can point you in the right direction. The place I would start is with DICe_Main.cpp, all of DICe pretty much branches off of there.

**Comment by SampanLee** [comment]
Thanks for your kind reply, and I will contact you if I have any question.
