### ISSUE TITLE
Image_Deformer Class

### ISSUE THREAD

**Issue by takmiyamott** [dicengine/dice#202]
I want to create the deformed images, especially with spatially varying displacement field like Sample 14 in DIC challenge.
Is it possible to generate such images using DICe?
I found Image_Deformer Class in the documentation: http://dicengine.github.io/dice/class_d_i_ce_1_1_image___deformer.html
but I don't understand how to use it!

**Comment by dicengine** [comment]
The image deformation tools in DICe are very primitive and weren't really intended for users to generate their own deformed images. More recently, we have been using Blender (www.blender.org) to create synthetically deformed images. The nice feature about Blender is that you can create stereo images, add noise, change camera parameters, and several other features that wouldn't be available using the Image_Deformer class in DICe.

**Comment by takmiyamott** [comment]
@dicengine Thanks for the useful information! I'll try Blender
