### ISSUE TITLE
Can you compute strains from an existing set out DICe output files (for example to do a VSG study)?

### ISSUE THREAD

**Issue by takmiyamott** [dicengine/dice#204]
@dicengine Hi. I have a results for displacement field. I would like to calculate strain field for various gauge sizes to check convergence. Is it possible to run the post processor using existing displacement field results?

**Comment by dicengine** [comment]
It's possible that the dice_strain executable is what you are looking for. The syntax is:
$: dice_strain source_file_1 ... source_file_n strain_window_size_in_pixels [target_locations_file] [ouput_prefix] [1: for use_nonlocal_formulation]

This tool hasn't been used in a while, and it's not part of the regression tests, but it might work. It looks like it is still being built and put in the bin folder.
