### ISSUE TITLE
Reg_paraview download

### ISSUE THREAD

**Issue by Poorva-creator** [dicengine/dice#207]
Hi team,

I am a new user of DICE-Github and want to use 'Paraview' for analyzing the results of DIC-stereo imaging.
Can you let me know which version of Paraview should I be downloading on my Mac operating system so as to do the analysis and proceed further.

Regards
Poorva

**Comment by Poorva-creator** [comment]
Also, where is the option of the color map editor ? It is required to allocate the global coordinates

**Comment by dicengine** [comment]
There isn't currently a color map editor, but that would be a good feature to add. I've added the enhancement tag to reflect this. The user is not required to add a global coordinate transform.

**Comment by Poorva-creator** [comment]
I am not able to calibrate using checkerboard option for stereo image analysis.

This is the file details:


<ParameterList>
<Parameter name="xml_file_format" type="string" value="DICe_xml_calibration_file" />
<Parameter name="image_folder" type="string" value="/Users/pjk/Desktop/DICe_Cal/" />
<Parameter name="image_file_extension" type="string" value=".jpg" />
<Parameter name="stereo_left_suffix" type="string" value="_0"/>
<Parameter name="stereo_right_suffix" type="string" value="_1"/>
<Parameter name="image_file_prefix" type="string" value="CalImage-" />
<Parameter name="reference_image_index" type="int" value="107" />
<Parameter name="start_image_index" type="int" value="107" />
<Parameter name="end_image_index" type="int" value="325" />
<Parameter name="skip_image_index" type="int" value="1" />
<Parameter name="num_file_suffix_digits" type="int" value="4" />
<Parameter name="cal_target_type" type="string" value="CHECKER_BOARD"/>
<Parameter name="cal_target_spacing_size" type="double" value="25.0"/>
<Parameter name="num_cal_fiducials_x" type="int" value="12"/>
<Parameter name="num_cal_fiducials_y" type="int" value="8"/>
<Parameter name="draw_intersection_image" type="bool" value="true"/>
<Parameter name="cal_debug_folder" type="string" value="/Users/pjk/Desktop/"/>
<Parameter name="threshold_start" type="int" value="69"/>
<Parameter name="threshold_end" type="int" value="69"/>
<Parameter name="threshold_step" type="int" value="69"/>
<Parameter name="use_adaptive_threshold" type="bool" value="true"/>
<Parameter name="block_size" type="int" value="75"/>
<ParameterList name="cal_opencv_options">
<Parameter name="CALIB_FIX_INTRINSIC" type="bool" value="false"/>
<Parameter name="CALIB_USE_INTRINSIC" type="bool" value="true"/>
<Parameter name="CALIB_USE_EXTRINSIC" type="bool" value="false"/>
<Parameter name="CALIB_FIX_PRINCIPAL_POINT" type="bool" value="false"/>
<Parameter name="CALIB_FIX_ASPECT_RATIO" type="bool" value="false"/>
<Parameter name="CALIB_SAME_FOCAL_LENGTH" type="bool" value="false"/>
<Parameter name="CALIB_ZERO_TANGENT_DIST" type="bool" value="true"/>
<Parameter name="CALIB_FIX_K1" type="bool" value="false"/>
<Parameter name="CALIB_FIX_K2" type="bool" value="false"/>
<Parameter name="CALIB_FIX_K3" type="bool" value="false"/>
</ParameterList>
</ParameterList>

**Comment by Poorva-creator** [comment]
<ParameterList>
<Parameter name="xml_file_format" type="string" value="DICe_xml_calibration_file" />
<Parameter name="image_folder" type="string" value="/Users/pjk/Desktop/DICe_Cal/" />
<Parameter name="image_file_extension" type="string" value=".jpg" />
<Parameter name="stereo_left_suffix" type="string" value="_0"/>
<Parameter name="stereo_right_suffix" type="string" value="_1"/>
<Parameter name="image_file_prefix" type="string" value="CalImage-" />
<Parameter name="reference_image_index" type="int" value="107" />
<Parameter name="start_image_index" type="int" value="107" />
<Parameter name="end_image_index" type="int" value="325" />
<Parameter name="skip_image_index" type="int" value="1" />
<Parameter name="num_file_suffix_digits" type="int" value="4" />
<Parameter name="cal_target_type" type="string" value="CHECKER_BOARD"/>
<Parameter name="cal_target_spacing_size" type="double" value="25.0"/>
<Parameter name="num_cal_fiducials_x" type="int" value="12"/>
<Parameter name="num_cal_fiducials_y" type="int" value="8"/>
<Parameter name="draw_intersection_image" type="bool" value="true"/>
<Parameter name="cal_debug_folder" type="string" value="/Users/pjk/Desktop/"/>
<Parameter name="threshold_start" type="int" value="69"/>
<Parameter name="threshold_end" type="int" value="69"/>
<Parameter name="threshold_step" type="int" value="69"/>
<Parameter name="use_adaptive_threshold" type="bool" value="true"/>
<Parameter name="block_size" type="int" value="75"/>
<ParameterList name="cal_opencv_options">
<Parameter name="CALIB_FIX_INTRINSIC" type="bool" value="false"/>
<Parameter name="CALIB_USE_INTRINSIC" type="bool" value="true"/>
<Parameter name="CALIB_USE_EXTRINSIC" type="bool" value="false"/>
<Parameter name="CALIB_FIX_PRINCIPAL_POINT" type="bool" value="false"/>
<Parameter name="CALIB_FIX_ASPECT_RATIO" type="bool" value="false"/>
<Parameter name="CALIB_SAME_FOCAL_LENGTH" type="bool" value="false"/>
<Parameter name="CALIB_ZERO_TANGENT_DIST" type="bool" value="true"/>
<Parameter name="CALIB_FIX_K1" type="bool" value="false"/>
<Parameter name="CALIB_FIX_K2" type="bool" value="false"/>
<Parameter name="CALIB_FIX_K3" type="bool" value="false"/>
</ParameterList>
</ParameterList>

**Comment by Poorva-creator** [comment]
It says, skipping due to the image being deactivated while trying for checkerboard calibration.

**Comment by dicengine** [comment]
Can you post some example cal images and a screen shot of the options you have selected?

**Comment by Poorva-creator** [comment]
Hi,

I figured out the issue. It was due to the incorrect input of total width and height !

Poorva

**Comment by Poorva-creator** [comment]
> There isn't currently a color map editor, but that would be a good feature to add. I've added the enhancement tag to reflect this. The user is not required to add a global coordinate transform.

There is an option for color map editor in the View section though!

Thanks 
Poorva
