### ISSUE TITLE
Can't skip files in calibration

### ISSUE THREAD

**Issue by micahsj00** [dicengine/dice#209]
Hello,
I don't seem to be able to see the list of files to be able to select and skip them for calibration. The "select files to skip" box is totally empty (I circled it in yellow on the screenshot).
![DICe issue_LI](https://user-images.githubusercontent.com/59046842/121744769-610ab780-cad1-11eb-8aa7-2f9bdb188eb8.jpg)

I'm not sure if I'm doing something wrong since I'm new to using DICe, or if it's a bug. Either way, any suggestions on how to fix the issue would be appreciated. Thanks!

**Comment by dicengine** [comment]
It could be that the marker dots were not located in any of the images so the list is empty. It looks like the left cal images are only half in the field of view. Is that correct? If so, you might need to take more cal images with all the dots visible.

**Comment by micahsj00** [comment]
I don't think it's that, since all of the dots are visible in all of the images, it just appears cut off because I zoomed in on the preview to get a closer look, sorry for the confusion there. All of the other images except the one in the screenshot are okay. They show up green and all of the dots are recognized. Here's what that image from the screenshot looks like zoomed out and without the threshold visible.
![Capture](https://user-images.githubusercontent.com/59046842/121746215-88628400-cad3-11eb-98d8-8bc784d52411.PNG)

**Comment by dicengine** [comment]
Thanks. In that case, the thresholding must not be working well in the right image. You should see a cyan box in the right image similar to the left with several dots identified by purple markers as well. One thing you can try is to uncheck the auto threshold box and try to manually select a threshold.

**Comment by micahsj00** [comment]
I was able to improve it with changing the threshold, thanks. So although I don't need to skip any images in this set of images, I predict that I will at some point. The "select files to skip" box is still empty, and is also empty when I select a different folder of calibration images, so it isn't a one off issue. Anything else I should try in order to solve this?

**Comment by micahsj00** [comment]
Ah I seem to have fixed it! I made all of the index numbers 2 digits (I put a zero before numbers 1 thru 9), and it seems like it works perfectly now!
