### ISSUE TITLE
Unable to build DICe properly under Windows using CMake

### ISSUE THREAD

**Issue by Slovarn** [dicengine/dice#224]
Hi,

I am trying to build DICe in order to use it as a library in an application i am writing in Visual Studio.
I followed the steps described [here](https://dicengine.github.io/dice/index.html) to build DICe with CMake under Windows.
I used dice version 2.0 as i don't know if tags with "-beta" are usable or if they are are still under tests. I also used the DiceDevPack_VS17 from the link you provide in your tutorial.

I did not get into any trouble during build (i had a few warnings that you can see below), but when i ran ctest command, 3 tests out of 135 failed (32-DICe_TestCalibration, 33-DICe_TestFeature and 80-DIFF_bitmap_star_DICe_solution0.txt).
I tried to go into the code of my application anyway. But when i try to declare a `DICe::Image` or a `DICe::Schema` with the signature containing a `Teuchos::ArrayRCP`, i get unresolved extern symbols.

Here is my code :
```
#include <iostream>
#include <iomanip>
#include <cstdio>

#include <cassert>

#include <DICe.h>
#include <DICe_Schema.h>

#include <Teuchos_RCP.hpp>
#include <Teuchos_oblackholestream.hpp>
#include <Teuchos_ParameterList.hpp>

int main(int argc, char* argv[])
{
	std::cout << "Test DICe" << std::endl;

	DICe::initialize(argc, argv);

	DICe::Image image(10, 10, 0);

	Teuchos::ArrayRCP<DICe::scalar_t> coordsX, coordsY;
	DICe::Schema schema(coordsX, coordsY, 10);

	DICe::finalize();

	return 0;
}
```
Nothing fancy as you can see.

And here are the errors :
![DICe error](https://user-images.githubusercontent.com/6115609/136293280-397284af-3c2b-471a-aa10-d3d4960fad1d.png)

I tried to go through all the registered issues but i did not manage to fix my problem.

Does this ring any bell ? Do you have some ideas about what i could have done wrong ?
I am sorry if i missed something obvious !

Thank you in advance !

**Comment by dicengine** [comment]
From the configuration output it looks like you are using the VS19 compiler. I’m not sure if there is a way to use the VS17 compiler, but that’s likely what’s going wrong. The failing tests are a bit of a red herring. That should be affect what you are trying to do with compiling.
