### ISSUE TITLE
invalid executable

### ISSUE THREAD

**Issue by YJ210810** [dicengine/dice#257]
Thanks for the software. I am running it on Win10. I have a problem when trying to run 2d as shown in the image.
![image](https://user-images.githubusercontent.com/105092896/167235889-ea7dad5f-8e24-4376-ae58-8249ec3b70cf.png)
The console indicate "writing parameters file C:\Users\Administrator\dice_working_dir\.dice\.dice\.dice\.dice\params.xml
params.xml file has been successfully saved
writing subset file C:\Users\Administrator\dice_working_dir\.dice\.dice\.dice\.dice\subset_defs.txt"

So I am wondering what's the problem?

**Comment by dicengine** [comment]
If you installed DICe in a non-standard folder, you have to update your .dice.js file to point to where the DICe executables were installed. 

`var execPathOverride = "Path to your DICe install";`

**Comment by YJ210810** [comment]
Thanks. That works. Best regards.

**Comment by YJ210810** [comment]
Thanks for the reply. The software is great!!
