### ISSUE TITLE
Location of axis of rotation

### ISSUE THREAD

**Issue by pvbhala** [dicengine/dice#262]
Hi 

I was curious if one can extract the location of the axis of rotation for the ROI. (Which can be different than the location of centroid of the ROI).

Thanks

**Comment by pvbhala** [comment]
Thanks for your response. For that I will need the displacement of different regions within the ROI. For this I ran the global analysis mode in the software but I am not able to read the .E result file. Could you help me out with this issue?

**Comment by dicengine** [comment]
You can read .e files with Paraview. You can likely export the info in a .e file to a csv file or something using paraview as well, but I haven't tried.
