### ISSUE TITLE
Correlation function algorithm of DICe software

### ISSUE THREAD

**Issue by chihyu722** [dicengine/dice#264]
Thanks to sandia lab provide this useful tool to analyze. 

my work is to be done and dusted, and I am writing a report.
I see the DICe reference manual below web. the report says that the correlation function is  zero-normalized cross-correlation, but from the representation of eq. (27) it feels more like zero-mean normalized sum of squared difference.
Am I got it wrong?

https://github.com/dicengine/dice/tree/master/doc/reports

**Comment by dicengine** [comment]
That's right it is ZNSSD.
