### ISSUE TITLE
Setting the correct calibration pattern options

### ISSUE THREAD

**Issue by lvmingzhi** [dicengine/dice#265]
![image](https://user-images.githubusercontent.com/112878439/188463850-ecff4c45-41fc-4ef9-84d7-6b8c1ea09dd2.png)
Hello, I want to ask how to solve the following situation

**Comment by dicengine** [comment]
Hi, Looks like you've got the wrong pattern dimensions for the pattern that you are using. From the images it looks like the total pattern width is 14, total pattern height is 10, inner pattern width is 10 and inner pattern height is 6 with an origin offset of 2 in x and 2 in y.

**Comment by lvmingzhi** [comment]
我按照您所说的，修改了图像尺寸，但还是出了问题
![image](https://user-images.githubusercontent.com/112878439/188536981-aee88e55-c98c-408d-a2b8-bee210a17e6e.png)

**Comment by lvmingzhi** [comment]
> 嗨，看起来你用的图案尺寸不对。从图像上看，总图案宽度为14，总图案高度为10，内部图案宽度为10，内部图案高度为6，原点偏移量为x为2，y为2。

根据您的建议，这一问题已经解决，但是想现在又出现了这样的问题，请问该如何解决
![image](https://user-images.githubusercontent.com/112878439/188552718-87de9828-7707-4f07-bc84-e2a144e7c28d.png)

**Comment by lvmingzhi** [comment]
> Hi, Looks like you've got the wrong pattern dimensions for the pattern that you are using. From the images it looks like the total pattern width is 14, total pattern height is 10, inner pattern width is 10 and inner pattern height is 6 with an origin offset of 2 in x and 2 in y.

Thank you very much. According to your suggestion, the problem just now has been solved, but now this problem has arisen. How can I solve it
![image](https://user-images.githubusercontent.com/112878439/188553148-b8a89348-4f33-4f92-ae90-4a7b48b4e6c9.png)

**Comment by dicengine** [comment]
What is the console output when it fails? If you click on the console tab you should get more information about why it failed.

**Comment by lvmingzhi** [comment]
> 失败时控制台的输出是什么？如果你点击控制台标签，你应该得到更多关于失败原因的信息。

Thank you. This problem has been solved. The Chinese and English paths do not match
