### ISSUE TITLE
Paraview output blank for the dice_solution.e file

### ISSUE THREAD

**Issue by nigel03256** [dicengine/dice#296]
I'm following the youtube tutorial from the DICE channel and tried replicating the steps to visualise the strain field in paraview but when I follow as instructed no output was seen in paraview. Is there a step I missed since I'm using Paraview version 5.11.0 on windows? I'm not very familiar with the paraview software, in honesty. Another thing I noticed is the data statistics is showing zero for most of the entries.
![image](https://github.com/dicengine/dice/assets/96030556/a32366d1-a4da-4974-a49a-64ec7f9666bc)
![image](https://github.com/dicengine/dice/assets/96030556/c4ce0426-29a2-44b2-9830-bfc1d12e546d)

**Comment by dicengine** [comment]
It seems that more recent versions of ParaView have changed the way they work with Exodus files. You might have to use an older version of ParaView until we figure out to get exodus output files working in the newer versions. Using v5.5.2 should work in the meantime.

**Comment by nigel03256** [comment]
Got it working. The latest version of paraview it works with is 5.9.1

**Comment by dicengine** [comment]
Update: There's a way to use the legacy Exodus II file reader in newer versions of ParaView (see https://gitlab.kitware.com/paraview/paraview/-/issues/21469)

Tools/ Manage Plugins/ LegacyExodusReader/ Load Selected
<img width="444" alt="Screenshot 2023-10-24 at 6 45 25 AM" src="https://github.com/dicengine/dice/assets/15202746/ac9cda1c-127b-4716-8488-1172fd063e26">
