### ISSUE TITLE
Ambiguity in calibration file specification

### ISSUE THREAD

**Issue by J-C-Haley** [dicengine/dice#297]
Hello and thank you in advance! I'm trying to wrap DICe with a ROS node for robotics applications, and I'm struggling to translate the camera calibration to the input xml. ROS uses a opencv description (defined here: http://docs.ros.org/en/melodic/api/sensor_msgs/html/msg/CameraInfo.html), but there's a couple ambiguities I was hoping you could clarify for me? I'm working off the example in https://github.com/dicengine/dice/blob/892496b466f4ecc50679f21db39b46cb3ac36a77/tests/regression/stereo_rectified/cal.xml, but if there's a better explanation I'd love to read it.

- First, are the translations Tx, Ty, and Tz in mm or pixel units? If cam0 is on the left, Tx should be positive correct? (this is opposite of the example)
- Are the focal lengths and image centers in for the raw or rectified image? fx or fx'? (in ROS, they provide both K and P respectively)
- Are the model coordinates of results in the cam0 (world) coordinate system, with +Z forward out of the camera (opencv convention)? 
- Is the rotation matrix for each camera the same as documented for opencv? Currently the epipolar lines only align and I only get results if I invert the rotation matrix for both cameras, but this seems to put the correlated points in the -Z direction, behind the camera... but if I have the baseline incorrect simultaneously 

Please let me know what you think, thank you very much!

**Comment by dicengine** [comment]
Hi James,

For calibration, Tx, Ty, and Tz are in physical coordiates. These are the physical distances of the cameras apart from each other as measured show in the triangulation report here: https://github.com/dicengine/dice/blob/master/doc/reports/Triangulation.pdf

Look at the figures in this report to get the signs right. Some will likely be negative according to the sign convention shown in Figure 2.

Focal lengths and centers are in raw.

The coordinate systems are also defined in the report.

The rotation matrix is also defined in the report, but in most cases, it's the transformation from camera 0 to camera 1.

Hopefully taking a look at the report above clears things up, but feel free to post a follow up question if not.

**Comment by J-C-Haley** [comment]
Ah, that clears a lot up, couldn't ask for better documentation. 

Looks like my assumptions were right about the units & using raw; I think the problem is that ROS defines the world coordinates not aligned with cam0, but rotated so that the baseline is along +X and and +Z is aligned. So ROS gives two rotations, one from world -> cam0 and one from world-> cam1, whereas unless I'm mistaken dice only wants one rotation, world/cam0 -> cam1. In the example dice xml, they have a identity rotation matrix for camera 0 as well, but if I intentionally screw it up it doesn't look like it affects anything, which would support this.

So, looks like I've got to put tx/ty/tz in the cam0 frame instead of world, and combine both rotations (cam0 -> world -> cam1, or R = R0^-1 R1). I'll try it next week and post how it goes, thanks again for the help!

**Comment by J-C-Haley** [comment]
Ok, there's something going on I can't explain from the documentation, and would greatly appreciate help.

Here's how I've interpreted the DICe coordinate systems:
![image](https://github.com/dicengine/dice/assets/68021474/ef0c5a3d-187e-4b5e-af4a-e7c5695adc86)
 
Where in the calibration.xml, the TX/TY/TZ are the translations from cam0/world to cam1, in the world coordinate system, in the model units (mm if results are mm). This is followed by a rotation, defined in the cal.xml as a matrix (dimensionless) or alpha/beta/gamma (degrees), about the cam1 origin. 

This does not sync up with what I've found in the examples however. In the tests/regression/stereo_rectified example, everything loads into the GUI and the epipolar lines project as expected, with Cam0 as left and Cam1 at the right. However:
- The TX is negative, whereas if the camera coordinate system were defined as openCV (+X right, +Y down, +Z out of camera toward model) it should be positive
- The commented beta euler rotation is positive (+35 deg), which if is going from world -> cam0, would point the cameras away from each other
- Additionally, if one substitutes the rotation matrix and uses the commented euler angles instead, the calibration is completely wrong. The calibration with euler angles doesn't work even if I use a different euler order (given appears to be ZYX, XYZ doesn't work either) or invert the direction. This leads me to think that euler angles are handled completely differently than a rotation matrix?

So, to boil this down into a couple questions:
- Are the camera coordinate systems defined the same as in opencv (+X to the right, etc)?
- Is the transform needed by the cal.xml actually Cam1 -> world? This would explain the negative TX and beta
- Why is there a difference in how rotation matrices and euler angles are interpreted in the calibration? 

Thank you again so much for the help!

**Comment by J-C-Haley** [comment]
Inverting the transform worked, mostly! The transform that needs to be entered into cal.xml is the Cam1 -> world transformation, like this:
![image](https://github.com/dicengine/dice/assets/68021474/a0e5b037-6cef-41ad-8a7c-cb6eb336f8be)

After inverting this, it agrees very well with the DICe produced calibration in magnitude and direction, despite it being the opposite to what the comments tell you to do... 
Here's some additional observations:
- When right clicking the left image, the epi line in the right appears perfect.
- When right clicking the right image, the epi line in the left is substantially wrong, and displaced vertically. This is true regardless of if it's a DICe calculated calibration or from ROS
- The world -> cam / cam -> world inversion is also flipped in the log output when calculating the calibration inside DICe

**Comment by dicengine** [comment]
Keep in mind that there is also a parameter in the cal.xml file "extrinsics_relative_camera_to_camera" that may be set or not set for some of the examples.

I'm not sure what's going on with the epi polar line, but it would suggest that the calibration parameters are not correct.

**Comment by J-C-Haley** [comment]
Good to know, I'm basing all this when that param is set to true, I'll have to test it.

I'm actually still having the same epi line mismatch on a DICe produced calibration as well, so I'm thinking it's actually not because of my translation anymore. Here's an example of what I'm seeing, zoomed in and right clicking on the keypoint of a calibration pattern. 

![image](https://github.com/dicengine/dice/assets/68021474/3f64778f-f5af-41a0-8ab0-621debbd912f)

The calibration reports average epipolar error of 0.3, which looks right when I right click the left image, but when I right click the right image it appears to be off by a good 80 pixels or so... would this be better as a separate issue?

**Comment by J-C-Haley** [comment]
Ok, I'm now able to reproduce a vanilla DICe calibration from the ROS calibration accurately (within ~0.25mm and ~0.2deg for cam extrinsics). Posting my code snippet in case anyone cares to reuse. 

NOTE that I did find that the transformation in the calibration is actually inverted, the translation and rotation are from right -> left, not left -> right after all (my second diagram). Maybe this gets inverted again inside DICe and something works out, but as it stands the calibration doesn't match the documentation. 

At this point, it looks like I'm not getting DICe to reconstruct due to initialization issues, may open another issue after trying some more things. Thanks again for all the help!

[convert_ros_to_dice_cal.txt](https://github.com/dicengine/dice/files/12137548/convert_ros_to_dice_cal.txt)
