### ISSUE TITLE
Could you please give the cal.txt text file format example, because I want to set the intrinsic and extrinsic by my self?

### ISSUE THREAD

**Issue by cxn304** [dicengine/dice#305]
As title

**Comment by dicengine** [comment]
Check out this example from the regression tests: https://github.com/dicengine/dice/blob/master/tests/regression/stereo_dogbone/cal.txt

All the parameters should be labeled in the example above.

**Comment by cxn304** [comment]
> Check out this example from the regression tests: https://github.com/dicengine/dice/blob/master/tests/regression/stereo_dogbone/cal.txt
> 
> All the parameters should be labeled in the example above, but as the example points out, using the xml file format is better since the .txt file is only available for legacy purposes. It should be too hard to copy one of the xml files (for example use this one: https://github.com/dicengine/dice/blob/master/tests/regression/stereo_rectified/cal.xml) and change the values for your problem.

thank you very much!
