### ISSUE TITLE
Calculation of SSSIG

### ISSUE THREAD

**Issue by sanpigh** [dicengine/dice#311]
Hello,

I'm running the 2D challenge 1.0 and I trying to obtain the SSSIG but I get a columns with sssig values equals to 0 like this:
SUBSET_ID,COORDINATE_X,COORDINATE_Y,DISPLACEMENT_X,DISPLACEMENT_Y,SIGMA,GAMMA,BETA,SSSIG
0,2.5000E+01,1.9000E+02,1.5040E+00,1.3597E+00,1.8046E-03,1.4296E-01,1.6892E-01,0.0000E+00
1,2.5000E+01,1.8500E+02,1.5158E+00,1.3495E+00,1.9121E-03,1.4788E-01,1.1534E-01,0.0000E+00
2,2.5000E+01,1.8000E+02,1.6867E+00,1.5602E+00,1.8929E-03,1.1748E-01,1.0385E-01,0.0000E+00
...................................................................................................................................................................... 

What is wrong in my params.xml? 

My params file is:

<ParameterList>
  <Parameter name="interpolation_method" type="string" value="KEYS_FOURTH"/>
  <Parameter name="initialization_method" type="string" value="USE_FIELD_VALUES" />

  <Parameter name="enable_translation" type="bool" value="true" />
  <Parameter name="enable_rotation" type="bool" value="true" />
  <Parameter name="enable_normal_strain" type="bool" value="true" />
  <Parameter name="enable_shear_strain" type="bool" value="true" />
  <Parameter name="output_delimiter" type="string" value="," />
  <Parameter name="gauss_filter_images" type="bool" value="false" />  
  <ParameterList name="post_process_vsg_strain">
    <Parameter name="strain_window_size_in_pixels" type="int" value="5"/>
  </ParameterList>
  <Parameter name="output_beta" type="bool" value="true" />

  <Parameter name="compute_image_gradients" type="bool" value="true" /> 
  

  <ParameterList name="output_spec">
    <Parameter name="COORDINATE_X" type="bool" value="true" />
    <Parameter name="COORDINATE_Y" type="bool" value="true" />
    <Parameter name="DISPLACEMENT_X" type="bool" value="true" />
    <Parameter name="DISPLACEMENT_Y" type="bool" value="true" />
    <Parameter name="VSG_STRAIN_XX" type="bool" value="true" />
    <Parameter name="VSG_STRAIN_YY" type="bool" value="true" />
    <Parameter name="SIGMA" type="bool" value="true" />
    <Parameter name="GAMMA" type="bool" value="true" />
    <Parameter name="BETA" type="bool" value="true" />
    <Parameter name="SSSIG" type="bool" value="true" />
  </ParameterList>
</ParameterList>
 

THANKS!

**Comment by dicengine** [comment]
Looks like the SSSIG field only gets populated for stereo, not 2D. I'll mark this as a bug and add it to the list of things to fix in the next version.

**Comment by sanpigh** [comment]
Thank you! 
Is there a doc with the quantities calculated under the fields FIELD_# ?

**Comment by dicengine** [comment]
Nope, the numbered fields are utility fields used for things like uncertainty analysis, etc. It just so happens that the SSSIG gets saved in one of those fields as part of the 2D analysis. Also, in some cases the same utility field might be used for two different purposes, hence no documentation on what they correspond to.
