### ISSUE TITLE
Question about the results of left and right camera matching

### ISSUE THREAD

**Issue by cxn304** [dicengine/dice#317]
Dear author,

I would like to inquire about the results of stereo vision matching between the left and right cameras in your software. Specifically, I am interested in the matching results for the individual subsets of the left and right cameras. In your result files, I have come across various parameters and measurements related to displacement, coordinates, model coordinates, and strain. However, I haven't found the specific information regarding the coordinate matching results for the subset of the left and right cameras. Could you please let me know where I can find this information? Thank you for your time and cooperation. I look forward to your response.

Best regards.

**Comment by dicengine** [comment]
I think what you are looking for is the CROSS_CORR_Q and CROSS_CORR_R fields in the exodus output, *.e. This is the coordinate matching information. Q is the horizontal displacement in pixels from the image coordinates in the left image to the image coordinates in the right image. R is the vertical.

**Comment by cxn304** [comment]
Thank you, could you tell me what encoding I should use to open this file?
![1710740058922](https://github.com/dicengine/dice/assets/33156791/eec0d62a-c298-4f3d-8049-13c745c86738)
