### ISSUE TITLE
Subsets highlighted in purple produce strange results

### ISSUE THREAD

**Issue by BenWor** [dicengine/dice#326]
Certain subsets along a diagonal line seem to produce strange results (see paraview image). I am expecting smooth results. These datapoints seem to be highlighted in the DICe image with purple dots. What does this mean?
![Screenshot 2024-05-20 at 17 35 30 (3)](https://github.com/dicengine/dice/assets/50152856/ddf8ec4b-1d64-4b19-b9c5-b172d87e230f)
![Screenshot 2024-05-20 at 17 41 08 (3)](https://github.com/dicengine/dice/assets/50152856/db6add42-4dbe-45e4-a902-2680e1954558)

**Comment by dicengine** [comment]
It could be a problem with the calibration or the initial cross-correlation. I see some warnings that the cross correlation initialization had some issues. What was the calibration error? Another thing you can check is right clicking on a point in the left or right image and checking if the epipolar line that shows up goes through that point in the stereo image. This is a quick check of the calibration parameters themselves.

**Comment by BenWor** [comment]
Thanks for the quick response. I've attached a screenshot of the calibration results window and a copy of the working directory files. 

https://drive.google.com/drive/folders/1KU9w98_IBP_F_cH0NHzss3MNk8JCblAC?usp=share_link

![Screenshot 2024-05-21 at 11 49 17 (3)](https://github.com/dicengine/dice/assets/50152856/06e0539b-4972-464f-b07c-75770ab3bc37)

I skipped images 1 and 2, as the first had a very large error (above 1), and the second was skipped automatically. I am unsure why these two images did not work because they are similar to images 3 and 4. Is it problematic that the calibration plate only takes up a small portion of the image?

When processing the cross-correlation, I get warnings in the console about the distortion parameters. What does this mean?

![Screenshot 2024-05-21 at 12 00 20](https://github.com/dicengine/dice/assets/50152856/aeb33adc-be18-4c5f-aa5f-f55a18860c63)

When I right-click on any of the purple points, the red line appears on the other image, indicating that the purple lines seem to lie along the epipolar line.

Thanks for your time.

**Comment by dicengine** [comment]
It's likely an issue with your calibration. Only 7 pairs of images might not be enough to get a good calibration. Typically, we use at least 20 or 30. Also, the calibration target should fill the field of view. The target you have in the image above only covers about 5% or less of the field of view. It would be nearly impossible to get the distortion parameters correct from this standoff distance. You want to hold the calibration plate close to the camera (like it is in the sample image in the middle of the GUI).  Another thing you can do to check your calibration is to add a couple fiducials to your sample where you know the distance between them or the position in space. Then you can check your output in DICe against that benchmark.
