### ISSUE TITLE
Filter Option for High Speed Cameras

### ISSUE THREAD

**Issue by aacruzc** [dicengine/dice#33]
Is it possible to set as an option to activate a filter that replaces all the pixels that reach the maximum (2^10 or 2^12) possible with adjacent pixels?  The user should be able to "disable" or "enable" the filter by a Boolean variable in the params.xml file.

Thanks.

Alvaro

**Comment by dicengine** [comment]
I've added an option, "filter_failed_cine_pixels" to do what you describe above. I'll create another release and email you when the installers are ready.
