### ISSUE TITLE
dice execution failed

### ISSUE THREAD

**Issue by astaraki** [dicengine/dice#45]
Thanks a lot for great software. I download the version 2 beta 5 and install it with windows 10.
After I load reference image, deform image, set roi and dic parameters, the dice execution failed.
There is not noticeable comment in the console.
I run the dice.exe file from the installation directory ,but the error "VCOMP120.DLL was not found"  is shown.
please help me for this problem
best regard.

**Comment by dicengine** [comment]
We'll check to be sure this library is included in the next release which will be two to three weeks.

**Comment by dicengine** [comment]
So I was wrong about the two-three week estimate above, but the latest release (2.0-beta.6) includes the missing .dll now.

**Comment by mpaes15** [comment]
Hi there, since yesterday, my DICe  version 3 beta 7 suddenly stop working and showing the message:
![image](https://user-images.githubusercontent.com/117855228/205078716-1a604c8c-5b5d-4af8-95fe-231458444151.png)

followed by text error:
invalid image dimensions, image load failure

The image files are numbered as 1.tiff, 2.tiff and so on.
Could you help me please?

**Comment by dicengine** [comment]
Did you install the DICe executable in the default folder?

**Comment by dicengine** [comment]
I was just checking that you didn't do something non-standard when you installed DICe, for example change the directory in Program Files where it gets installed. Sounds like that's not the case.

**Comment by mpaes15** [comment]
not really

**Comment by mpaes15** [comment]
So, what you recommend?

**Comment by dicengine** [comment]
Can you walk me through the steps you take, beginning with opening DICe, that lead up to the error message you get?

**Comment by mpaes15** [comment]
Hi there, I found out the problem. The images used were in .tiff extension. After conversion to .tif, it started work again. Thanks
