### ISSUE TITLE
Version 2.0-beta.5 issue

### ISSUE THREAD

**Issue by bvanmieg** [dicengine/dice#46]
I  installed the 2.0 beta 5 version from the installer packages on a windows 10 (64 bit) machine. After loading the ref. and def. images and selecting a ROI I try to correlate (all other opties stay default). I immediately get following message : DICe execution failed (see console for details).

When looking at the console, the only messages I get are:
writing input file C:\PATH\input.xml
input.xml file has been successfully saved
writing parameters file C:\PATH\params.xml
params.xml file has been successfully saved
writing subset file C:\PATH\subset_defs.txt
subset_defs.txt file has been successfully saved

For the rest everything looks normal.
Please advise what I'm doing wrong.
Thanks
Bart

**Comment by dicengine** [comment]
Hi,


If you use a command prompt tool and go into the C:\PATH\ folder, what do you get if you run the following command: $ <path_to_dice_exe>\dice.exe -i input.xml -v ?


This will tell me if there is a library missing or something else is wrong. The path to dice.exe should be somewhere in Program Files or wherever you installed it.


Thanks,

Dan


________________________________

**Comment by bvanmieg** [comment]
Hi Dan,


Thanks for the prompt reply.

I tried what you suggested and I get a system failure stating that the VCOMP120.dll is missing.


Sounds familiar?


Thanks,

Bart


________________________________
Van: Digital Image Correlation Engine (DICe) <notifications@github.com>
Verzonden: maandag 28 augustus 2017 11:32:34
Aan: dicengine/dice
CC: bvanmieg; Author
Onderwerp: Re: [dicengine/dice] Version 2.0-beta.5 issue (#46)

Hi,


If you use a command prompt tool and go into the C:\PATH\ folder, what do you get if you run the following command: $ <path_to_dice_exe>\dice.exe -i input.xml -v ?


This will tell me if there is a library missing or something else is wrong. The path to dice.exe should be somewhere in Program Files or wherever you installed it.


Thanks,

Dan


________________________________

**Comment by dicengine** [comment]
Hi Bart,

That’s what I was expecting. For some reason that .dll isn’t on some Windows 10 systems. We’re going to package it with DICe in the official release of Version 2. Unfortunately, that has been delayed. We’re shooting for an updated installed for version 2 to be available before the end of the year. Sorry for the inconvenience.

Thanks,
Dan

**Comment by bvanmieg** [comment]
Hi Dan,

That's a pity. I'm looking forward to the new release and will be willing to help debugging.

Is there a way that I can add the dll to the sourcecode and compile again myself? Do you have a procedure for that?

Thanks
Bart

Op 28 aug. 2017 10:55 p.m. schreef "Digital Image Correlation Engine (DICe)" <notifications@github.com>:
Hi Bart,

That’s what I was expecting. For some reason that .dll isn’t on some Windows 10 systems. We’re going to package it with DICe in the official release of Version 2. Unfortunately, that has been delayed. We’re shooting for an updated installed for version 2 to be available before the end of the year. Sorry for the inconvenience.

Thanks,
Dan

**Comment by dicengine** [comment]
Hi Bart,

If you install the missing dll in either the system path or the DICe folder in program files, it should work without a re-compile. I haven’t tried this, but if you can locate a trusted copy of the dll it’s worth a try.

I’ll keep you posted on an updated installer.

Thanks,
Dan

**Comment by bvanmieg** [comment]
Hi Dan,

I found the dll and was able to run the correlation without problems.
I'm looking forward though to the next release.

Thanks for the support.

Bart


Op 29 aug. 2017 4:43 p.m. schreef "Digital Image Correlation Engine (DICe)" <notifications@github.com>:
Hi Bart,

If you install the missing dll in either the system path or the DICe folder in program files, it should work without a re-compile. I haven’t tried this, but if you can locate a trusted copy of the dll it’s worth a try.

I’ll keep you posted on an updated installer.

Thanks,
Dan

**Comment by dicengine** [comment]
Hi Bart,

Great. Thanks for letting me know and I’ll keep you posted.

-Dan
