### ISSUE TITLE
Strange full-field strain results

### ISSUE THREAD

**Issue by kenaycock** [dicengine/dice#47]
Hi DICe team, 

I'm attempting to run the full-field strain tutorial (example 3) using the latest version of the GUI (2.0-5) on MacOS 10.11.6

I load the reference and deformed images from the tutorial and define inclusion/exclusion regions as below:
![input_1](https://user-images.githubusercontent.com/5925722/32019574-ad8eaaf8-b99b-11e7-891d-38323ec038a0.png)
with the following processing options:
![input_2](https://user-images.githubusercontent.com/5925722/32019575-ad98c0c4-b99b-11e7-9786-f4981e41e025.png)

The displacement data look reasonable, but the computed strain field is quite noisy and doesn't make a lot of sense:
![output](https://user-images.githubusercontent.com/5925722/32019576-ada7d46a-b99b-11e7-9b95-5f46d58c1529.png)

I've tried a few different combinations of settings, but the strain results look similar to that above regardless. I also tried previous versions of the 2.0 beta (2.0-3, 2.0-4), but it seemed like the Exodus output was corrupt in these versions (at least with a small step size). 

Are there any known issues with the strain results in the current Mac release?

Kind regards,
Ken

**Comment by dicengine** [comment]
Hi Ken,

Thanks for your email. My impression is that your strain window size is too small (gauge size: 3 pixels), I would expand that considerably to at least 7 or 11 pixels. Try that and let me know if it works.

Thanks,
Dan

**Comment by kenaycock** [comment]
Hi Dan, 

Thank you for the response. Increasing the gauge size does indeed smooth the strains (e.g., gauge size of 10px below). 
![screen shot 2017-10-25 at 6 24 21 pm](https://user-images.githubusercontent.com/5925722/32026481-9cebed98-b9b2-11e7-8cfb-9b7c8caf663b.png)

I guess this is just not what I expected the strain field to look like. Is this a uniaxial tension test, or something else? 

Anyway, I have another question, but I will start a new issue. Thanks again! 

Ken

**Comment by dicengine** [comment]
Hi Ken,

I think you’re right that the results still seem strange. The plot below is for the YY strain and yes, this is a uniaxial tension test so the YY strains should be small. I’m assuming that this image is an early one in the sequence. If that’s true, I would anticipate that the strains produced would be very noisy, like they are in the image below, because the signal to noise ratio is still very small. Once the deformation increases, these noisy results should go away as the signal emerges.

Thanks,
Dan

**Comment by kenaycock** [comment]
Hi Dan, others:

Just to confirm, here are results from another DIC software (Ncorr) with similar DIC parameters (subset size 31px, step size 1px, and strain window of 10px) for comparison:
![dice_ex3_results_ncorr](https://user-images.githubusercontent.com/5925722/32030299-03caa274-b9c8-11e7-8d97-f9191684be98.png)

The results look qualitatively similar, although the noise in the strain field differs a bit between the two.

Thanks,
Ken
