### ISSUE TITLE
"Large" translations not recognized

### ISSUE THREAD

**Issue by kenaycock** [dicengine/dice#48]
Hi Dan and team, 

I am performing some more tests with DICe and have noticed that large translations (>~30px) between two image frames are not recognized.

For instance, in the following image pair,<sup>*</sup> a simple rigid-body translation is applied (32-pixel shift to the left):
<img src="https://user-images.githubusercontent.com/5925722/32065738-95b84c12-ba4b-11e7-8764-c4be5a282ed8.png" width="100">
<img src="https://user-images.githubusercontent.com/5925722/32065746-98685da8-ba4b-11e7-8fd6-81e6930b3a07.png" width="100">

Feature matching initialization seems to work fine:
<img src="https://user-images.githubusercontent.com/5925722/32065972-424026d0-ba4c-11e7-9c9c-43226726c6a5.png" width="200">

but the displacement field is empty:
<img src="https://user-images.githubusercontent.com/5925722/32066661-876f560c-ba4e-11e7-856f-4dded4b8be59.png" width="700">
 
The behavior seems to be independent of subset and step size, initialization method, etc. But if a smaller (e.g., 20px) translation is applied instead, the displacements are extracted as expected. 

Any ideas as to why this is occurring? Is there a way to overcome this limitation? 

Thanks, 
Ken

<sup>*</sup>Note: source image from Pan et al. 2010, *Opt Lasers Eng.*

**Comment by dicengine** [comment]
Hi Ken,

The reason is that there is a max-displacement check to ensure that the subset optimization routine doesn’t accidentally lock on to a potential match far away in the image. The default value is 25 pixels, which explains why 20 px works below, but not 30. 

All you need to do is add a parameter to the params.xml file:

<Parameter name="disp_jump_tol" type="double" value="100.0" />

That should fix it. (There is a similar parameter for rotation “theta_jump_tol” if you have large rotations too).

Thanks,
Dan

**Comment by kenaycock** [comment]
Hi Dan, 

Ah! That explains a lot! Thank you for tip. 

However, whenever I run an analysis, the GUI overwrites 'params.xml'. Is there a way to set these parameters with the GUI version? I've considered running from the terminal, but I'm not able to locate the 'dic' executable within the package bundle.

Ken

**Comment by dicengine** [comment]
Hi Ken,

Depending on whether you are running on Windows or Mac/Linux the install location is different. On a mac, the standard location is Applications/DICe.app/Contents/Resources/app/bin/dice for Windows, it’s C:\Program Files (x86)\Digital Image Correlation Engine\dice.exe

The command line syntax is $: dice(.exe) -i input.xml -v

We should probably expose the max-displacement jump or make the default a huge number to prevent similar issues for other people. For now, I’ll increase the max dramatically for the next release.

Hope that helps,

Dan

**Comment by kenaycock** [comment]
Hi Dan, 

I'm running on a Mac and found the executable where you indicated. I updated my params.xml file (attached) and re-ran the analysis from the terminal. The results look much better. 

Thanks for the help!

Ken
