### ISSUE TITLE
Undefined reference issues when building DICe

### ISSUE THREAD

**Issue by bvanmieg** [dicengine/dice#52]
I have an issue that looks similar to issue #49. I work onUbuntu 16.04 LTS
I installed:
- Lapack 3.7.1
-Libtiff 4.0.8
- Boost 1.65.1
- Trillinos (using a slightly modified do-trillinos-cmake file from the scripts)
So far everything goes well.

Building DICe (2.0 update 6) also goes well with the do-cmake file from the scripts

When trying to make I get following error though:

27% Linking CXX executable ../../bin/dice
../../lib/libdicecore.a(DICe_Initializer.cpp.o): In function `DICe::Feature_Matching_Initializer::pre_execution_tasks()':
DICe_Initializer.cpp:(.text+0x7299): undefined reference to `DICe::match_features(Teuchos::RCP<DICe::Image>, Teuchos::RCP<DICe::Image>, std::vector<float, std::allocator<float> >&, std::vector<float, std::allocator<float> >&, std::vector<float, std::allocator<float> >&, std::vector<float, std::allocator<float> >&, float const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/usr/local/DICe/lib/libdiceutils.a(DICe_ImageIO.cpp.o): In function `DICe::utils::write_image(char const*, int, int, float*, bool, bool)':
DICe_ImageIO.cpp:(.text+0x152c): undefined reference to `png_set_IHDR'
DICe_ImageIO.cpp:(.text+0x153d): undefined reference to `png_write_info'
DICe_ImageIO.cpp:(.text+0x18f5): undefined reference to `png_write_row'
DICe_ImageIO.cpp:(.text+0x191a): undefined reference to `png_write_end'
DICe_ImageIO.cpp:(.text+0x193b): undefined reference to `png_destroy_write_struct'
DICe_ImageIO.cpp:(.text+0x1b86): undefined reference to `TIFFOpen'
DICe_ImageIO.cpp:(.text+0x1ba8): undefined reference to `TIFFSetField'

and this list keeps on going on with undefined references
At the end it ends with:

/usr/local/lapack/lib/liblapack.a(sormbr.f.o):sormbr.f:(.text+0x4b9): more undefined references to `_gfortran_concat_string' follow
/usr/local/lapack/lib/liblapack.a(xerbla.f.o): In function `xerbla_':
xerbla.f:(.text+0x79): undefined reference to `_gfortran_st_write'
xerbla.f:(.text+0x90): undefined reference to `_gfortran_string_len_trim'
xerbla.f:(.text+0xb3): undefined reference to `_gfortran_transfer_character_write'
xerbla.f:(.text+0xd1): undefined reference to `_gfortran_transfer_integer_write'
xerbla.f:(.text+0xe0): undefined reference to `_gfortran_st_write_done'
xerbla.f:(.text+0xef): undefined reference to `_gfortran_stop_string'
/usr/local/lapack/lib/liblapack.a(dgesvd.f.o): In function `dgesvd_':
dgesvd.f:(.text+0x44e): undefined reference to `_gfortran_concat_string'
dgesvd.f:(.text+0x128b): undefined reference to `_gfortran_concat_string'
/usr/local/lapack/lib/liblapack.a(dhseqr.f.o): In function `dhseqr_':
dhseqr.f:(.text+0x5f5): undefined reference to `_gfortran_concat_string'
/usr/local/lapack/lib/liblapack.a(dormbr.f.o): In function `dormbr_':
dormbr.f:(.text+0x366): undefined reference to `_gfortran_concat_string'
dormbr.f:(.text+0x403): undefined reference to `_gfortran_concat_string'
/usr/local/lapack/lib/liblapack.a(dormbr.f.o):dormbr.f:(.text+0x4b9): more undefined references to `_gfortran_concat_string' follow
collect2: error: ld returned 1 exit status
src/core/CMakeFiles/dice_main.dir/build.make:126: recipe for target 'bin/dice' failed
make[2]: *** [bin/dice] Error 1
CMakeFiles/Makefile2:182: recipe for target 'src/core/CMakeFiles/dice_main.dir/all' failed
make[1]: *** [src/core/CMakeFiles/dice_main.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

Any clue what I'm doing wrong?

Thanks

**Comment by dicengine** [comment]
Unfortunately, I don't have an Ubuntu system to try and replicate this on. Here is what I use on RHEL for my do-cmake script. Not sure if this helps or not...

#!/bin/bash                                                                                                                                                               
EXTRA_ARGS=$@

rm -f CMakeCache.txt
rm -rf CMakeFiles

cmake \
 -D CMAKE_BUILD_TYPE=RELEASE \
 -D CMAKE_INSTALL_PREFIX:FILEPATH=/scratch/code/DICe/build_global/install \
 -D DICE_TRILINOS_DIR:FILEPATH=/scratch/code/trilinos_nightly/build_mpi_release/install \
 -D DICE_DEBUG_MSG:BOOL=OFF \
 -D CMAKE_VERBOSE_MAKEFILE:BOOL=OFF \
 -D DICE_USE_DOUBLE:BOOL=ON \
 -D DICE_USE_TPETRA:BOOL=OFF \
 -D DICE_ENABLE_MANYCORE:BOOL=OFF \
 -D DICE_ENABLE_GLOBAL:BOOL=ON \
 -D CMAKE_CXX_FLAGS:STRING="-lgfortran -Wall -Werror -Wno-deprecated-declarations -Wno-unused-local-typedefs -Wno-literal-suffix" \
 -D OpenCV_DIR:PATH=/scratch/code/opencv-3.2.0/build/install \
 -D BOOST_ROOT:FILEPATH=/scratch/software/boost_1_55_0/build \
 -D NetCDF_DIR:PATH=/scratch/code/netcdf/build/install/lib \
 -D HDF5_DIR:PATH=/scratch/code/hdf5/build/lib \
$EXTRA_ARGS ../

**Comment by dicengine** [comment]
I've created an Ubuntu virtual machine and compiled and tested DICe successfully using the instructions found here: http://dicengine.github.io/dice/#BuildingDICe. There are also example configuration scripts to use in the /scripts/ubuntu folder, that were added recently. Let me know if that solves your problem. If not, I'll re-open this issue.

**Comment by bvanmieg** [comment]
Hey,

That solved the issues!
I could build it without problems now.

Bart

Op 18 dec. 2017 4:14 p.m. schreef "Digital Image Correlation Engine (DICe)" <notifications@github.com>:

I've created an Ubuntu virtual machine and compiled and tested DICe successfully using the instructions found here: http://dicengine.github.io/dice/#BuildingDICe. There are also example configuration scripts to use in the /scripts/ubuntu folder, that were added recently. Let me know if that solves your problem. If not, I'll re-open this issue.

**Comment by bvanmieg** [comment]
Hi,

For some reason I had to format my PC and reinstall the DICE code from scratch. I tried to build again from source on Ubuntu using the instructions you mention and everything goes smooth until the "$ make all install" of DICE.
I get a similar error as the one I had before:

[ 27%] Built target dicecore
[ 28%] Linking CXX executable ../../bin/dice
../../lib/libdicecore.a(DICe_Initializer.cpp.o): In function `DICe::Feature_Matching_Initializer::pre_execution_tasks()':
DICe_Initializer.cpp:(.text+0x8749): undefined reference to `DICe::match_features(Teuchos::RCP<DICe::Image>, Teuchos::RCP<DICe::Image>, std::vector<double, std::allocator<double> >&, std::vector<double, std::allocator<double> >&, std::vector<double, std::allocator<double> >&, std::vector<double, std::allocator<double> >&, float const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
collect2: error: ld returned 1 exit status
src/core/CMakeFiles/dice_main.dir/build.make:145: recipe for target 'bin/dice' failed
make[2]: *** [bin/dice] Error 1
CMakeFiles/Makefile2:184: recipe for target 'src/core/CMakeFiles/dice_main.dir/all' failed
make[1]: *** [src/core/CMakeFiles/dice_main.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

Any clues where I should look for to fix this?

Regards,
Bart

**Comment by dicengine** [comment]
Hi Bart,

When you installed the image libraries, did you use the -dev variants?

Thanks,
Dan

On Apr 7, 2018, at 2:47 PM, bvanmieg <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,

For some reason I had to format my PC and reinstall the DICE code from scratch. I tried to build again from source on Ubuntu using the instructions you mention and everything goes smooth until the "$ make all install" of DICE.
I get a similar error as the one I had before:

[ 27%] Built target dicecore
[ 28%] Linking CXX executable ../../bin/dice
../../lib/libdicecore.a(DICe_Initializer.cpp.o): In function DICe::Feature_Matching_Initializer::pre_execution_tasks()': DICe_Initializer.cpp:(.text+0x8749): undefined reference toDICe::match_features(Teuchos::RCPDICe::Image, Teuchos::RCPDICe::Image, std::vector<double, std::allocator >&, std::vector<double, std::allocator >&, std::vector<double, std::allocator >&, std::vector<double, std::allocator >&, float const&, std::__cxx11::basic_string<char, std::char_traits, std::allocator > const&)'
collect2: error: ld returned 1 exit status
src/core/CMakeFiles/dice_main.dir/build.make:145: recipe for target 'bin/dice' failed
make[2]: *** [bin/dice] Error 1
CMakeFiles/Makefile2:184: recipe for target 'src/core/CMakeFiles/dice_main.dir/all' failed
make[1]: *** [src/core/CMakeFiles/dice_main.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

Any clues where I should look for to fix this?

Regards,
Bart

**Comment by bvanmieg** [comment]
Hi Dan,

I double-checked:

$ sudo apt-get install libtiff-dev libpng-dev libjpeg-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'libtiff5-dev' instead of 'libtiff-dev'
Note, selecting 'libpng12-dev' instead of 'libpng-dev'
libjpeg-dev is already the newest version (8c-2ubuntu8).
libpng12-dev is already the newest version (1.2.54-1ubuntu1).
libtiff5-dev is already the newest version (4.0.6-1ubuntu0.4).
0 upgraded, 0 newly installed, 0 to remove and 16 not upgraded.

Except that he retrieves different versions, it seems that I installed the -dev versions.

Regards,
Bart

**Comment by bvanmieg** [comment]
Hi Dan,

I found the issue and was able to build and test succesfully.
I by mistake added a space in front of the filepath references in one of the do-cmake scripts.

Thanks for the feedback though.

Bart

**Comment by dicengine** [comment]
Great. Thanks for letting me know.

-Dan

On Apr 9, 2018, at 5:17 PM, bvanmieg <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Dan,

I found the issue and was able to build and test succesfully.
I by mistake added a space in front of the filepath references in one of the do-cmake scripts.

Thanks for the feedback though.

Bart
