### ISSUE TITLE
error in compiling DICE

### ISSUE THREAD

**Issue by zhoug15** [dicengine/dice#68]
I am a new user of DICE, and i had all the dependencies well installed in ubuntu 16.04.
I run cmake and configure and generate dice-master in Builds.
Then, there are errors when make Builds.

Here is the output in terminal:

zhouqian@ubuntu:~/OpenSource/dice-master/Builds$ sudo make
[sudo] password for zhouqian: 
Scanning dependencies of target DICe_utils
[  0%] Performing configure step for 'DICe_utils'
loading initial cache file /home/zhouqian/OpenSource/dice-master/Builds/utils_tmp/DICe_utils-cache-.cmake

Configuring DICe utils...

BUILD_SHARED_LIBS is set to OFF

Found Trilinos!  Here are the details: 
   Trilinos_DIR = /usr/local/lib/cmake/Trilinos
   Trilinos_VERSION = 12.2.2
   Trilinos_PACKAGE_LIST = 
   Trilinos_LIBRARIES = 
   Trilinos_INCLUDE_DIRS = 
   Trilinos_LIBRARY_DIRS = 
   Trilinos_TPL_LIST = Pthread
   Trilinos_TPL_INCLUDE_DIRS = 
   Trilinos_TPL_LIBRARIES = 
   Trilinos_TPL_LIBRARY_DIRS = 
   Trilinos_BUILD_SHARED_LIBS = OFF
End of Trilinos details

-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- CMAKE_BUILD_TYPE: 
CMake Warning at /usr/share/cmake-3.5/Modules/FindBoost.cmake:725 (message):
  Imported targets not available for Boost version 106501
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindBoost.cmake:763 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake-3.5/Modules/FindBoost.cmake:1332 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:86 (find_package)

CMake Warning at /usr/share/cmake-3.5/Modules/FindBoost.cmake:725 (message):
  Imported targets not available for Boost version 106501
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindBoost.cmake:763 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake-3.5/Modules/FindBoost.cmake:1332 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:86 (find_package)

CMake Warning at /usr/share/cmake-3.5/Modules/FindBoost.cmake:725 (message):
  Imported targets not available for Boost version 106501
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindBoost.cmake:763 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake-3.5/Modules/FindBoost.cmake:1332 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:86 (find_package)

-- Boost version: 1.65.1
-- Found the following Boost libraries:
--   program_options
--   system
--   filesystem
-- Tiff file format enabled. Using tiff library from /usr/local/lib/libtiff.a
-- Could not find jpeg library. Jpeg file format is NOT enabled
Could not find png library. Png file format is NOT enabled
-- Using Boost libraries from: /usr/local/lib and inlcudes from: /usr/local/include
-- Debugging messages are OFF
-- Image intensity and scalar type will be: FLOAT (default)
-- c++11 was enabled in Trilinos so enabling it here. (Found flag at position 6)
-- Trilinos CMAKE_CXX_FLAGS:  -std=c++11 -O3
-- Trilnos CMAKE_C_FLAGS:  -O3
-- DICe CMAKE_CXX_FLAGS:   -O3  -std=c++11
-- DICe CMAKE_C_FLAGS: 
-- diceutils library will be output to location: 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/zhouqian/OpenSource/dice-master/Builds/utils_build
[  1%] Performing build step for 'DICe_utils'
Scanning dependencies of target diceutils
[ 25%] Building CXX object src/CMakeFiles/diceutils.dir/DICe_ImageIO.cpp.o
In file included from /home/zhouqian/OpenSource/dice-master/src/utils/src/./DICe_ImageIO.h:46:0,
                 from /home/zhouqian/OpenSource/dice-master/src/utils/src/DICe_ImageIO.cpp:45:
/home/zhouqian/OpenSource/dice-master/src/utils/src/../../cine/DICe_Cine.h:54:27: fatal error: Teuchos_RCP.hpp: No such file or directory
compilation terminated.
src/CMakeFiles/diceutils.dir/build.make:62: recipe for target 'src/CMakeFiles/diceutils.dir/DICe_ImageIO.cpp.o' failed
make[5]: *** [src/CMakeFiles/diceutils.dir/DICe_ImageIO.cpp.o] Error 1
CMakeFiles/Makefile2:85: recipe for target 'src/CMakeFiles/diceutils.dir/all' failed
make[4]: *** [src/CMakeFiles/diceutils.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make[3]: *** [all] Error 2
CMakeFiles/DICe_utils.dir/build.make:111: recipe for target '../src/utils/src/DICe_utils-stamp/DICe_utils-build' failed
make[2]: *** [../src/utils/src/DICe_utils-stamp/DICe_utils-build] Error 2
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/DICe_utils.dir/all' failed
make[1]: *** [CMakeFiles/DICe_utils.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

Sorry for my poor English...

**Comment by dicengine** [comment]
I'm setting up a VM to get a build going on Ubuntu. I'll provide installation instructions when I get something that works.

**Comment by dicengine** [comment]
Looks like you maybe didn't run the 
$ make install 
command when you built Trilinos. DICe find_package Trilinos doesn't have any of the varaibles populated. For example the packages installed in Trilinos. Try following the build instructions that were just added to the documentation for Ubuntu and see if that helps.
