### ISSUE TITLE
Custom application on Ubuntu + python plot for stereo correlation

### ISSUE THREAD

**Issue by bvanmieg** [dicengine/dice#71]
1- Would be nice to have an example of the DICe_CustomApplication that works on Ubuntu.
I tried to build the application following the example that is online now, but without success. I get similar errors as the ones when building DICe on Ubuntu (which I managed to build in the meanwhile following your guidance).

2- Is there somewhere a python script available to plot stereo correlation data? I can only find examples for 2D data.

3-Is there a script available to plot a certain value as function of the result file. I have now a number of separate result files with data (one for each image), but I would like to plot for example the displacement in a certain area of the image as function of the image number?

**Comment by dicengine** [comment]
I've updated the build instructions for a DICe custom application. I've also included a new sample cmake script in the DICe/scripts folder that seems to work fine, following the new instructions on Ubuntu. There was also a commit to the cmake files for DICe that now includes a missing header file. A fresh pull of DICe along with a build install should be all that you need to get started on the custom app on Ubuntu. I'll close this issue for now, but we can re-open it if this doesn't work for you.

I'm also going to move the other two requests to separate issues for bookkeeping...

**Comment by bvanmieg** [comment]
Thanks for the updates.
I tried to build the custom example but have issues with HDF5:

CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
HDF5_hl_lib
    linked by target "main" in directory /home/bvm/dice_working_dir/custom_app
HDF5_lib
    linked by target "main" in directory /home/bvm/dice_working_dir/custom_app

-- Configuring incomplete, errors occurred!

I installed HDF5 (1.10.1) and referred to that in the do-custom-app-cmake script but without success.
Any help would be more than welcome.
Regards,
Bart

**Comment by dicengine** [comment]
The problems building the custom app on Ubuntu should be resolved from a cmake standpoint with commit d4f9621. Let me know if it still doesn't work with that update.
