### ISSUE TITLE
DICE V2.0 Isssue 7 windows install correlation error stereo example

### ISSUE THREAD

**Issue by bvanmieg** [dicengine/dice#76]
I get following error when running the stereo DIC example:

--Correlation parameters read successfully --
C:\Users\dzturne\Software\DICe_nightly\scr\core\DICe_Parser.cpp:696:

Throw number= 1

Throw test that evaluated to true: digits <=0

**Comment by dicengine** [comment]
Hi,

Can you provide some more context? Is this during a calibration or for the actual stereo correlation? And which file select method are you using (select individually, sequence of images, etc)?


On Jan 30, 2018, at 3:38 PM, bvanmieg <notifications@github.com<mailto:notifications@github.com>> wrote:


I get following error when running the stereo DIC example:

--Correlation parameters read successfully --
C:\Users\dzturne\Software\DICe_nightly\scr\core\DICe_Parser.cpp:696:

Throw number= 1

Throw test that evaluated to true: digits <=0

**Comment by bvanmieg** [comment]
The issue appeared during correlation but it's solved in the meanwhile.
Recalibrating solved the issue, the calibration quality was not really good.
I'll close this one.
