### ISSUE TITLE
Subset throwing error related to image extent

### ISSUE THREAD

**Issue by dtseidl** [dicengine/dice#77]
[PROC 0] Owns subset global id (in order): 0 neighbor id: -1

[DICe_DEBUG]: [PROC 0] Adding objective to obj_vec_ 0
/Users/dtseidl/src/dice/src/base/DICe_ImageSerial.cpp:270:

Throw number = 1

Throw test that evaluated to true: x<0||x>=width_

**Comment by dicengine** [comment]
Commit 0a13600 should fix this issue, let me know if you still have problems.
