### ISSUE TITLE
custom application HDF5 issues

### ISSUE THREAD

**Issue by bvanmieg** [dicengine/dice#78]
Hi Dan,

Building DICE from source works perfect now on Ubuntu 16.04 LTS.

When trying to build the custom application however (with the doc-cmake script in the ubuntu folder) I keep on getting errors on HDF5 (not found).
Can you suggest a location where I can get a decent version of DHF5 and the necessary dependencies?

Thanks,
Bart

**Comment by dicengine** [comment]
Hi Bart,

Here’s the link to HDF5: https://support.hdfgroup.org/HDF5/release/obtain518.html if you want to build it from source. On ubuntu you could try

sudo apt-get install libhdf5-serial-dev

although I haven’t verified that this will work.

Thanks,
Dan

On Apr 16, 2018, at 4:55 AM, bvanmieg <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Dan,

Building DICE from source works perfect now on Ubuntu 16.04 LTS.

When trying to build the custom application however (with the doc-cmake script in the ubuntu folder) I keep on getting errors on HDF5 (not found).
Can you suggest a location where I can get a decent version of DHF5 and the necessary dependencies?

Thanks,
Bart

**Comment by bvanmieg** [comment]
Thanks again Dan, I built it from source and now the custom application is running fine.
Bart
