### ISSUE TITLE
Error in building source files in Ubuntu

### ISSUE THREAD

**Issue by iniyanakila** [dicengine/dice#81]
Hi

I first thank you for the code.

When I tried to build from source in Ubuntu linux as per the step-by-step instruction given in http://dicengine.github.io/dice/, I ended up with the following error.

[ 27%] Building CXX object src/core/CMakeFiles/dice_strain.dir/DICe_Strain.cpp.o
make[2]: *** No rule to make target '/usr/lib/liblapack.so.3', needed by 'bin/dice_strain'.  Stop.
CMakeFiles/Makefile2:184: recipe for target 'src/core/CMakeFiles/dice_strain.dir/all' failed
make[1]: *** [src/core/CMakeFiles/dice_strain.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

DICe_Strain.cpp file build has failed. 
Am I missing something here? As I mentioned above, I followed every step in the instructions given to build in Ubuntu Linux.

Thanks,
Iniyan.

**Comment by dicengine** [comment]
Did you install liblapack-dev? Seems you might not have the developer libraries installed.


sudo apt-get install libblas-dev liblapack-dev


On May 30, 2018, at 9:03 AM, iniyanakila <notifications@github.com<mailto:notifications@github.com>> wrote:

No rule to make target '/usr/lib/liblapack.so.3',

**Comment by iniyanakila** [comment]
Hi,

Thanks for your reply. 

I realized that I had been working with Ubuntu 18.04 LTS and therefore, those files were installed in a different directory. I updated the correct location in the DICe make files, but, new error popped up while compiling /home/shankar_sj/Downloads/dice-master/tools/DICeDiff.cpp 

Finally, I started with a fresh install of Ubuntu 16.04 LTS and then followed the step-by-step instruction given in http://dicengine.github.io/dice/

It all worked fine. I thank you for the clear instructions, too.

Cheers,
Iniyan.

**Comment by sleach3** [comment]
Is there a solution to fixing this issue on Ubuntu 18.04. I ran into the same issue while installing and will not be able to do a fresh install with Ubuntu 16.04.

**Comment by dicengine** [comment]
What is the error you are getting hung up on?
On Jul 10, 2019, at 3:03 PM, Clay <notifications@github.com<mailto:notifications@github.com>> wrote:


Is there a solution to fixing this issue on Ubuntu 18.04. I ran into the same issue while installing and will not be able to do a fresh install with Ubuntu 16.04.

**Comment by sleach3** [comment]
I am getting hung on the same error as the original poster. 
` 27%] Building CXX object src/core/CMakeFiles/dice_strain.dir/DICe_Strain.cpp.o
make[2]: *** No rule to make target '/usr/lib/liblapack.so.3', needed by 'bin/dice_strain'. Stop.
CMakeFiles/Makefile2:184: recipe for target 'src/core/CMakeFiles/dice_strain.dir/all' failed
make[1]: *** [src/core/CMakeFiles/dice_strain.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2`

I am using Ubuntu 18.04.

**Comment by dicengine** [comment]
Do you have the developer libraries installed for lapack?

On Jul 10, 2019, at 7:44 PM, Clay <notifications@github.com<mailto:notifications@github.com>> wrote:


I am getting hung on the same error as the original poster.
27%] Building CXX object src/core/CMakeFiles/dice_strain.dir/DICe_Strain.cpp.o make[2]: *** No rule to make target '/usr/lib/liblapack.so.3', needed by 'bin/dice_strain'. Stop. CMakeFiles/Makefile2:184: recipe for target 'src/core/CMakeFiles/dice_strain.dir/all' failed make[1]: *** [src/core/CMakeFiles/dice_strain.dir/all] Error 2 Makefile:129: recipe for target 'all' failed make: *** [all] Error 2

I am using Ubuntu 18.04.

**Comment by sleach3** [comment]
I have installed liblapack-dev which are the latest version (3.7.1-4ubuntu1)

**Comment by dicengine** [comment]
Somehow the lapack libraries aren’t being found. In the existing cmake process in DICe, the lapack libraries get included based on the Trilinos configuration, but you could try adding a find_package call to DICe to look for lapack on your system.

Try adding: FIND_PACKAGE(lapack required) to the top level CMakeLists.txt file.


On Jul 11, 2019, at 7:45 AM, Clay <notifications@github.com<mailto:notifications@github.com>> wrote:


I have installed liblapack-dev which are the latest version (3.7.1-4ubuntu1)

**Comment by sleach3** [comment]
I have added that to CMakeLists.txt and got the following message. I don't have a lot of experience with these types of issues and am not sure how to go from here. 
`CMake Error at CMakeLists.txt:54 (FIND_PACKAGE):
  By not providing "Findlapack.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "lapack", but
  CMake did not find one.

  Could not find a package configuration file provided by "lapack" with any
  of the following names:

    lapackConfig.cmake
    lapack-config.cmake

  Add the installation prefix of "lapack" to CMAKE_PREFIX_PATH or set
  "lapack_DIR" to a directory containing one of the above files.  If "lapack"
  provides a separate development package or SDK, be sure it has been
  installed.


-- Configuring incomplete, errors occurred!
`

**Comment by dicengine** [comment]
You can look where you have lapack installed to see if the cmake configuration files mentioned below exist. If they do exist, you can change the find_package call to FIND_PACKAGE(lapack PATHS <path to the .cmake files for lapack here> ). If those files don’t exist we’ll have to try another plan.



On Jul 11, 2019, at 11:11 AM, Clay <notifications@github.com<mailto:notifications@github.com>> wrote:


I have added that to CMakeLists.txt and got the following message. I don't have a lot of experience with these types of issues and am not sure how to go from here.
`CMake Error at CMakeLists.txt:54 (FIND_PACKAGE):
By not providing "Findlapack.cmake" in CMAKE_MODULE_PATH this project has
asked CMake to find a package configuration file provided by "lapack", but
CMake did not find one.

Could not find a package configuration file provided by "lapack" with any
of the following names:

lapackConfig.cmake
lapack-config.cmake


Add the installation prefix of "lapack" to CMAKE_PREFIX_PATH or set
"lapack_DIR" to a directory containing one of the above files. If "lapack"
provides a separate development package or SDK, be sure it has been
installed.

-- Configuring incomplete, errors occurred!
`

**Comment by sleach3** [comment]
I searched the location where lapack is installed and was unable to find any cmake files for lapack. Will I need to try and build it myself?

**Comment by dicengine** [comment]
That’d definitely an option and here’s a page that tells how to do it: https://coral.ise.lehigh.edu/jild13/2016/07/27/install-lapack-and-blas-on-linux-based-systems/

The thing you want to be careful of here is that you will then have two versions of this library on your system that may not be compatible. When the code is linked, it could potentially use the system installed version for Trilinos, and then your local version when compiling DICe. I’m not sure if that would screw things up, but if it did the resulting error could be really whacky, like exiting without any info on why the code crashed. If you do install another version of lapack, recompile Trilinos and make sure it’s pointed to the right lapack.

**Comment by sleach3** [comment]
Thank you very much for your help. I will try the rebuild and see if I can get it working.

**Comment by bvanmieg** [comment]
I was able to install DICe on Ubuntu 18.04LTS. Please have a look at the required modifications in: https://github.com/dicengine/dice/issues/136

Bart

**Comment by sandilyasg** [comment]
> lapack is installed and was unable to find any cmake files for lapa

I am facing the same issue where I used `sudo apt install liblapack-dev libblas-dev ` but I am getting the same error:
```
CMake Error at /usr/share/cmake-3.10/Modules/FindLAPACK.cmake:361 (message):
  A required library with LAPACK API not found.  Please specify library
  location.
Call Stack (most recent call first):
  slam_toolbox/slam_toolbox/CMakeLists.txt:43 (find_package)
```
@dicengine @sleach3 how do you ensure it is linked to the right lapack? Were you able to solve this, please help.
