### ISSUE TITLE
Errors when compile the DICe

### ISSUE THREAD

**Issue by fengzekang** [dicengine/dice#86]
![default](https://user-images.githubusercontent.com/38140045/43998761-0446a52a-9e30-11e8-9c79-8a68df4b4168.JPG)
@dicengine Hello,why there is an error when I compile the DICe,I don't know the reason why it happened.
Best regards.
fengzekang

**Comment by dicengine** [comment]
Hi,

Did you install DICe in the default directory? If not, the analysis executable may not be located correctly.

Thanks,
Dan

**Comment by fengzekang** [comment]
Dear @dicengine 
Thanks for your reply.I think I have solved the last error.But when I tried to run the analysis after I load the ref and def pictures,there is a new error as followed:
loading GUI state and preferences from C:\Users\KkkTtt\.dice.js
checking if input requirements met to enable running DICe ...
left reference image not set yet
deformed images have not been defined yet
right reference image not set yet
What should I do to solve this error?
Best regards.
fengzekang

**Comment by dicengine** [comment]
I’m not sure on this one…have you defined both the left and right images if you are running stereo?
-Dan

**Comment by fengzekang** [comment]
Dear @dicengine 
Sorry for my late reply.These days I will use the DICe to deal with some images to show the distance and other results. But after I load the reference and the deformed with the examples pictures,there are some errors occured:
Console output: 

loading GUI state and preferences from C:\Users\KkkTtt\.dice.js
checking if input requirements met to enable running DICe ...
deformed images have not been defined yet
right reference image not set yet
checking if input requirements met to enable running DICe ...
right reference image not set yet
input requirements successful
writing input file C:\Users\KkkTtt\Desktop\DICe_Solution\input.xml
input.xml file has been successfully saved
writing parameters file C:\Users\KkkTtt\Desktop\DICe_Solution\params.xml
params.xml file has been successfully saved
writing subset file C:\Users\KkkTtt\Desktop\DICe_Solution\subset_defs.txt
I can not solve the error.Could you please help me?
Best regards.

**Comment by dicengine** [comment]
Hi,

It looks like you just need to load the reference and deformed images from the right camera. Have you loaded both when you get the error?

Also, on the GitHub page for DICe, there are some videos that show how to set up an analysis. Have you watched the stereo video yet?

Thanks,
Dan

**Comment by fengzekang** [comment]
Dear @dicengine @dtseidl 
I didn't solve the problem until now.There is always an error showed that no right/left image loaded.But I didn't set two camares.
![error](https://user-images.githubusercontent.com/38140045/46212845-9266e780-c369-11e8-8119-ba8290ae88d8.png)

input.xml file has been successfully saved
writing parameters file C:\Users\KkkTtt\Desktop\DICe_Solution\test\params.xml
params.xml file has been successfully saved
writing subset file C:\Users\KkkTtt\Desktop\DICe_Solution\test\subset_defs.txt
checking if input requirements met to enable running DICe ...
right reference image not set yet
input requirements successful
writing input file C:\Users\KkkTtt\Desktop\DICe_Solution\test\input.xml
input.xml file has been successfully saved
writing parameters file C:\Users\KkkTtt\Desktop\DICe_Solution\test\params.xml
params.xml file has been successfully saved
writing subset file C:\Users\KkkTtt\Desktop\DICe_Solution\test\subset_defs.txt

On the other people's computer,there is not the error,but on my computer errors occured.

**Comment by dicengine** [comment]
One thing you could try is to erase the .dice.js file in your home directory and try again. There may be a bad setting saved in this file.

-Dan

**Comment by fengzekang** [comment]
@dicengine After I delate the file,the software changed to like this:
![_20180928231511](https://user-images.githubusercontent.com/38140045/46217515-c562a880-c374-11e8-924c-34f4a2a6e660.png)

And then I load the images as the reference and deformed,but there is not the "run2d" appeared.

**Comment by fengzekang** [comment]
![_20180928231848](https://user-images.githubusercontent.com/38140045/46217550-e0351d00-c374-11e8-9742-770f61c2902f.png)

**Comment by dicengine** [comment]
For some reason, I can't see the text in your comment above. Can you repost the comment with just the text and no image?

**Comment by dicengine** [comment]
At this point, I would delete the .dice.js file in your home directory and try running DICe again. If that doesn't work let me know and I'll re-open this issue.
