### ISSUE TITLE
New errors in the processing

### ISSUE THREAD

**Issue by fengzekang** [dicengine/dice#88]
Hello @dicengine 
After I load the images,I set the previewer threshold button,there is an error occoured as below
![_20180930154957](https://user-images.githubusercontent.com/38140045/46254871-c1479f80-c4c8-11e8-9773-03e00d5a1101.png)
I can't sovle the problem.What should I do to deal with it?
Best regards

**Comment by dicengine** [comment]
If you installed DICe in a non-standard location, you have to change some default settings in the global.js file that exists in your DICe install dir. There should be a variable at the top of the file to set your path to where you installed it. If that doesn't work, let me know and I'll re-open this issue.
