### ISSUE TITLE
Calibration error

### ISSUE THREAD

**Issue by hannahsuthers** [dicengine/dice#89]
When I try to run "2d" I get this error message...?
![issues](https://user-images.githubusercontent.com/43452254/46432144-7f626780-c71b-11e8-965e-55ee96a55373.JPG)

I tried searching for calibration issues on here, but no luck and I can't find the option within DICe. 

Thanks!

**Comment by dicengine** [comment]
Hi,

It looks like the contrast of the images is too low for the feature matching initializer to work. Is it possible to upload a sample image so I can see what’s going on. 

Otherwise, you can try changing the initialization scheme USE_FIELD_VALUES to see if that works.

Thanks,
Dan

**Comment by hannahsuthers** [comment]
Hey,

Ahh okay. Here's my reference image. I'm trialling DICe to compare it to other softwares before I complete my research experiments, so unfortunately the image isn't ideal I know. I have got results with the same image though GOM Correlate. 

![image](https://user-images.githubusercontent.com/43452254/46432837-36abae00-c71d-11e8-8006-cf98763f1905.png)

Thanks for the help
Hannah

**Comment by dicengine** [comment]
Hi Hannah,

Thanks. Seems like you should be able to get some results if you change the initialization option to USE_FIELD_VALUES. Let me know if that works.

Thanks,
Dan

On Oct 3, 2018, at 1:03 PM, hannahsuthers <notifications@github.com<mailto:notifications@github.com>> wrote:


Hey,

Ahh okay. Here's my reference image. I'm trialling DICe to compare it to other softwares before I complete my research experiments, so unfortunately the image isn't ideal I know. I have got results with the same image though GOM Correlate.

[image]<https://user-images.githubusercontent.com/43452254/46432837-36abae00-c71d-11e8-8006-cf98763f1905.png>

Thanks for the help
Hannah

**Comment by Pulsar9000** [comment]
Hi, try using this updated version. It might solve your feature detection problem. 

https://github.com/dicengine/dice/releases/tag/v2.0-beta.12

**Comment by dicengine** [comment]
I'm assuming that the updates to the feature matching routine fix this, if not, let me know and I'll re-open this issue
