### ISSUE TITLE
Error creating  the file

### ISSUE THREAD

**Issue by longisit** [dicengine/dice#94]
Hello, I'm new to using the application.

I have conducted trials several times using example images. Initially the first few experiments I conducted run smoothly and the plot was display.

I did not alter any setting in the application or computer but just now when I try to new trial with same batch of images it shows this:
![screen shot 2018-11-24 at 9 09 29 pm](https://user-images.githubusercontent.com/45313335/48969225-73fe2f00-f02e-11e8-9833-b7d772bd1ead.png)
![screen shot 2018-11-24 at 9 09 21 pm](https://user-images.githubusercontent.com/45313335/48969227-76f91f80-f02e-11e8-9b06-02db4ada6610.png)
![screen shot 2018-11-24 at 9 09 14 pm](https://user-images.githubusercontent.com/45313335/48969228-78c2e300-f02e-11e8-8990-cce6ba5d2e3b.png)

Can anyone please help me solve this?

**Comment by dicengine** [comment]
Hi,

Seems like maybe your working directory got fouled up somehow, this is stored in the .dice.js file in your home directory. If that file got corrupted or moved, the working directory would be undefined and lead to DICe trying to create these files on the disk root directory ‘//‘. Check if the .dice.js file exists in your home directory and if so see what the workingDirectory variable is.

Thanks,
Dan

On Nov 24, 2018, at 7:20 AM, longisit <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello, I'm new to using the application.

I have conducted trials several times using example images. Initially the first few experiments I conducted run smoothly and the plot was display.

I did not alter any setting in the application or computer but just now when I try to new trial with same batch of images it shows this:
[screen shot 2018-11-24 at 9 09 29 pm]<https://user-images.githubusercontent.com/45313335/48969225-73fe2f00-f02e-11e8-9833-b7d772bd1ead.png>
[screen shot 2018-11-24 at 9 09 21 pm]<https://user-images.githubusercontent.com/45313335/48969227-76f91f80-f02e-11e8-9b06-02db4ada6610.png>
[screen shot 2018-11-24 at 9 09 14 pm]<https://user-images.githubusercontent.com/45313335/48969228-78c2e300-f02e-11e8-8990-cce6ba5d2e3b.png>

Can anyone please help me solve this?

**Comment by dicengine** [comment]
Hi, I'm assuming that either modifying or deleting your .dice.js file in your home directory worked. If not, let me know and I'll re-open this issue.
