### ISSUE TITLE
Unable to detect features

### ISSUE THREAD

**Issue by Pulsar9000** [dicengine/dice#95]
I have successfully worked with DICe in high resolution images, however I have problem using images from other camera. 

I have attached a copy of two images (Img_1 and Img_2) as example, I used them in DICe feature detection mode to get the error "num_matches< 10". 

**NOTE:** DICe works for the same images if the entire image are considered for analysis, but fails if the region of interest is between the two black bands. The result given by DICe is in the file name fm_initializer_0, input and parameters are also included in the folder.

However, I tried to detect features using a small python cv2 program, it gave approx 13000 matching features screen shot in image CV2_Manual_trial. 

Why am I not able to detect more than 10 features using DICe? 
[Files.zip](https://github.com/dicengine/dice/files/2615907/Files.zip)

**Comment by dicengine** [comment]
The reason is that the default tolerance for the feature matching is set too high. If I manually change the tolerance, DICe finds a similar number of features as your python results. We should probably add a dial in the input parameters for the feature matching tolerance when the default fails or re-do the feature matching with different tolerances until one works. I'll see how hard this would be to add to the code.

**Comment by dicengine** [comment]
Thanks for the suggestion. It looks like from the documentation for the c++ opencv implementation that the default is 0.001f as the tolerance if you remove the threshold arg, and doesn't use an adaptive method for the AKAZE: https://docs.opencv.org/3.4/d8/d30/classcv_1_1AKAZE.html. I'll look into it more, but it seems like adjusting the tolerance if the first iteration fails is working well for now. I'll push the commit for this soon.

**Comment by Pulsar9000** [comment]
Hi again, I understand that you might want to fix more than just 1 bug in your next version. Since, I'm overloaded with data waiting to be processed (it could also help for further clarification of this function),  I would be happy if you push a new build as soon as possible.

**Comment by dicengine** [comment]
I updated the installers to have the commits that should help with this issue. Here's the link: https://github.com/dicengine/dice/releases/tag/v2.0-beta.12
