### ISSUE TITLE
Execution fails without error statements in console (due to uninitialized value in openCV AKAZE feature matching)

### ISSUE THREAD

**Issue by Pulsar9000** [dicengine/dice#96]
I have attached two images and the parameters used in the zip folder below. which has found reasonable amount of features matched, nevertheless the program stops with no reasons mentioned in the console.

NOTE: These images are taken at 1 second time interval and this images are approximately 20 sec after the test begun. 

![save](https://user-images.githubusercontent.com/45360452/49651462-89f8f000-fa2f-11e8-846c-ad6aefae0e0f.PNG)
[Example.zip](https://github.com/dicengine/dice/files/2657515/Example.zip)

**Comment by dicengine** [comment]
I memory profiled a DICe run with your example files and uncovered an uninitialized value in opencv's AKAZE feature matching routine that causes the issue you note above. On linux and mac your example runs fine, but on Windows the uninitialized value causes DICe to crash.

I need to think about what the best way to address this. There might be another setting we can use with AKAZE that doesn't suffer from this uninitialized value. Another alternative is to submit a bug fix request to opencv. Let me do some more digging on this.

**Comment by dicengine** [comment]
I just pushed a workaround for this issue and updated the installers for v2.0-beta.12. I tested it on the problem you attached above and it works for me on mac, linux, and windows. I'll go ahead and close this issue. Let me know if you have any trouble.

**Comment by Pulsar9000** [comment]
Thank you for the update that was very quick. I tested the new update on three test experiments which had the same problem, it works for all. I confirm that this new updates solves this problem :+1:
