### ISSUE TITLE
DICe build fails, VideoWriter was not declared in this scope

### ISSUE THREAD

**Issue by linglingdeshenpang** [dicengine/dice#97]
Hi,
Thanks for your codes. I build DICe for source code. I installed opencv and trilinos  successfully. But i can not make DICe successfully.

There is the problem.
/home/XXX/Desktop/DICE/dice/tools/DICe_TrackingMovieMaker.cpp:263:3: error: ‘VideoWriter’ was not declared in this scope
   VideoWriter video(movie_name.str(),-1,10, Size(img_w,img_h));
   ^~~~~~~~~~~
/home/XXX/Desktop/DICE/dice/tools/DICe_TrackingMovieMaker.cpp:354:5: error: ‘video’ was not declared in this scope
     video.write(out_img);
     ^~~~~
/home/XXX/Desktop/DICE/dice/tools/DICe_TrackingMovieMaker.cpp:356:3: error: ‘video’ was not declared in this scope
   video.release();
   ^~~~~
[ 32%] Linking CXX executable ../bin/DICe_CineStat
/usr/bin/ld: cannot find -ldiceutils
collect2: error: ld returned 1 exit status
tools/CMakeFiles/DICe_CineStat.dir/build.make:133: recipe for target 'bin/DICe_CineStat' failed
make[2]: *** [bin/DICe_CineStat] Error 1
CMakeFiles/Makefile2:430: recipe for target 'tools/CMakeFiles/DICe_CineStat.dir/all' failed
make[1]: *** [tools/CMakeFiles/DICe_CineStat.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
tools/CMakeFiles/DICe_TrackingMovieMaker.dir/build.make:62: recipe for target 'tools/CMakeFiles/DICe_TrackingMovieMaker.dir/DICe_TrackingMovieMaker.cpp.o' failed
make[2]: *** [tools/CMakeFiles/DICe_TrackingMovieMaker.dir/DICe_TrackingMovieMaker.cpp.o] Error 1
CMakeFiles/Makefile2:356: recipe for target 'tools/CMakeFiles/DICe_TrackingMovieMaker.dir/all' failed
make[1]: *** [tools/CMakeFiles/DICe_TrackingMovieMaker.dir/all] Error 2

**Comment by dicengine** [comment]
I forgot to update the build scripts after enabling the video output for the tracking routines. You need to enable videoio when you build opencv now. The ubuntu opencv do-opencv-cmake file has been updated to turn this on.

In your opencv do-cmake script, change the line "-D BUILD_opencv_videoio=OFF" to ON, and rebuild and install opencv. Then re-build DICe.

**Comment by linglingdeshenpang** [comment]
Thx, it worked. I rebuild successfully.
