### ISSUE TITLE
Non-realistic Strain readings

### ISSUE THREAD

**Issue by Pulsar9000** [dicengine/dice#98]
I'm using, Version 2.0 beta .12 version after issue #96.

I have previously processed few tests like the one shown below using DICe, we call it cyclic creep recovery. 
For this test, I have compared three typed of strain readings:
1. Contact Extensometer reading (blue);
2. DIC using nCorr (red) (np.mean on the load direction strain field or find mean by fitting normal distribution on the load direction strain fields );
3. DICe (yellow)(np.mean on the the load direction strain field or find mean by fitting normal distribution on the load direction strain fields).

DIC nCorr and DICe are almost close all the time. 
NOTE: DICe is definitely robost and better! 

![example_classic](https://user-images.githubusercontent.com/45360452/49800881-f2eea980-fd48-11e8-966f-55fcf2295cd0.jpg)

However, for one particular test, though the contact extensometer (blue) reading have proper creep and recovery profile mean DICe strain reading (red) did not give a similar profile.
![full_image](https://user-images.githubusercontent.com/45360452/49801175-bff8e580-fd49-11e8-84f9-ad9b035d652f.jpg)

The test contains ~5000 images in total, therefore I have cropped (181 images) one block where I suspect the test fails (after compression stage) as an example for the developers. The plot below shows the strain readings that I observed at the cropped block.
1. Contact Extensometer reading (blue);
2. DIC using nCorr (red) (mean strain on x direction strain fields);
3. DICe (yellow)(mean strain on x direction strain fields).

![crop_compare](https://user-images.githubusercontent.com/45360452/49808225-5209e980-fd5c-11e8-9b04-5ed941d849ac.jpg)

I see that even the mean value of nCorr is behaving strangely. One assumption is this test is strange in total and should be deleted, nevertheless I couldn't get the same min max values on comparing nCorr and DICe. Give me your comments regarding it, and if you could do something within your program do let me know.

Additional information:
1. I have noticed that this problem occurs only after compression stage;
2. I see that the min strain at this region is below -49%;
3. The strain profile appears to be reversed. Therefore, I tried to calculate by selecting the image with highest strain as reference image. The strain profile was still reversed but the min strain did not reach abnormal values (4% max and -2% min);

I have uploaded the following files in the link below:
Image folder -181 images
DICe folder - parameters of DICe, python script to calculate mean from DICe output
Extenso.csv - time and  strain measured by extensometer at same time instance
DICe.csv - time and mean strain on DICe strain field (X direction)
DIC_ncorr.csv - time and mean strain on nCorr strain field (X direction)

https://drive.google.com/drive/folders/1kIHkCcdZZxoqmKfJ1NgBGHMDg5hlbUbL?usp=sharing

**Comment by dicengine** [comment]
I'm not sure how you have the extensometer attached in your experiment, but my guess is that the sample slipped in the grips. I ran the images you provided in the link above in DICe with debugging output so I could see the residuals and see if any warnings got triggered and was able to produce similar results to yours without any warnings.  I'll keep thinking about it, but there must be something physical going on with the test set up.

**Comment by Pulsar9000** [comment]
I have not found the source of the problem yet, I will check and let you know asap. You may close the issue, I would re-open it if I realize the problem is not from the experimental setup.
